const addresses = [
  {
    street_address: "14302 Messerschmidt Way",
    city: "Columbus",
    zip_code: "31998",
    state: "Georgia",
    country: "United States",
  },
  {
    street_address: "3 Petterle Terrace",
    city: "Houston",
    zip_code: "77281",
    state: "Texas",
    country: "United States",
  },
  {
    street_address: "17 Thierer Drive",
    city: "Winston Salem",
    zip_code: "27150",
    state: "North Carolina",
    country: "United States",
  },
  {
    street_address: "84 Mariners Cove Parkway",
    city: "Philadelphia",
    zip_code: "19191",
    state: "Pennsylvania",
    country: "United States",
  },
  {
    street_address: "9403 Londonderry Street",
    city: "Cincinnati",
    zip_code: "45208",
    state: "Ohio",
    country: "United States",
  },
  {
    street_address: "10079 Glendale Center",
    city: "Minneapolis",
    zip_code: "55417",
    state: "Minnesota",
    country: "United States",
  },
  {
    street_address: "15593 Lakewood Gardens Park",
    city: "Warren",
    zip_code: "44485",
    state: "Ohio",
    country: "United States",
  },
  {
    street_address: "544 Petterle Pass",
    city: "Waco",
    zip_code: "76796",
    state: "Texas",
    country: "United States",
  },
  {
    street_address: "62 3rd Court",
    city: "Cincinnati",
    zip_code: "45228",
    state: "Ohio",
    country: "United States",
  },
  {
    street_address: "7379 Thompson Place",
    city: "Tacoma",
    zip_code: "98405",
    state: "Washington",
    country: "United States",
  },
  {
    street_address: "50 Northport Road",
    city: "Singapore",
    zip_code: null,
    state: null,
    country: "Singapore",
  },
  {
    street_address: "8 Sauthoff Plaza",
    city: "Singapore",
    zip_code: null,
    state: null,
    country: "Singapore",
  },
  {
    street_address: "5 Golf View Parkway",
    city: "Singapore",
    zip_code: null,
    state: null,
    country: "Singapore",
  },
  {
    street_address: "4 Sycamore Pass",
    city: "Singapore",
    zip_code: null,
    state: null,
    country: "Singapore",
  },
  {
    street_address: "54208 Trailsway Crossing",
    city: "Singapore",
    zip_code: null,
    state: null,
    country: "Singapore",
  },
  {
    street_address: "50157 Dennis Road",
    city: "Kashima-shi",
    zip_code: "314-0048",
    state: null,
    country: "Japan",
  },
  {
    street_address: "104 Buena Vista Plaza",
    city: "Ichinomiya",
    zip_code: "941-0056",
    state: null,
    country: "Japan",
  },
  {
    street_address: "40 Prairieview Avenue",
    city: "Tōkamachi",
    zip_code: "949-8612",
    state: null,
    country: "Japan",
  },
  {
    street_address: "6 Sloan Park",
    city: "Nayoro",
    zip_code: "607-8077",
    state: null,
    country: "Japan",
  },
  {
    street_address: "76 Veith Center",
    city: "Kokubu-matsuki",
    zip_code: "584-0024",
    state: null,
    country: "Japan",
  },
  {
    street_address: "6 Troy Park",
    city: "Peachland",
    zip_code: "B3S",
    state: "British Columbia",
    country: "Canada",
  },
  {
    street_address: "417 Maywood Point",
    city: "Devon",
    zip_code: "T9G",
    state: "Alberta",
    country: "Canada",
  },
  {
    street_address: "7916 Stuart Park",
    city: "Marieville",
    zip_code: "J3M",
    state: "Québec",
    country: "Canada",
  },
  {
    street_address: "5515 Donald Alley",
    city: "Hearst",
    zip_code: "S4A",
    state: "Ontario",
    country: "Canada",
  },
  {
    street_address: "17888 Meadow Ridge Center",
    city: "Kitimat",
    zip_code: "V8C",
    state: "British Columbia",
    country: "Canada",
  },
  {
    street_address: "1545 Homewood Pass",
    city: "Emiliano Zapata",
    zip_code: "48892",
    state: "Jalisco",
    country: "Mexico",
  },
  {
    street_address: "0048 Knutson Point",
    city: "Lindavista",
    zip_code: "29557",
    state: "Chiapas",
    country: "Mexico",
  },
  {
    street_address: "19 Manufacturers Lane",
    city: "Santa Rosa",
    zip_code: "67803",
    state: "Nuevo Leon",
    country: "Mexico",
  },
  {
    street_address: "38872 Talisman Street",
    city: "Benito Juarez",
    zip_code: "66410",
    state: "Nuevo Leon",
    country: "Mexico",
  },
  {
    street_address: "521 Michigan Street",
    city: "Emiliano Zapata",
    zip_code: "70805",
    state: "Oaxaca",
    country: "Mexico",
  },
  {
    street_address: "5 Eastlawn Pass",
    city: "Capitão Poço",
    zip_code: "68650-000",
    state: null,
    country: "Brazil",
  },
  {
    street_address: "6 Rusk Way",
    city: "Boa Esperança",
    zip_code: "87390-000",
    state: null,
    country: "Brazil",
  },
  {
    street_address: "6887 Truax Crossing",
    city: "Itatinga",
    zip_code: "18690-000",
    state: null,
    country: "Brazil",
  },
  {
    street_address: "48727 Morningstar Trail",
    city: "Quirinópolis",
    zip_code: "75860-000",
    state: null,
    country: "Brazil",
  },
  {
    street_address: "1063 Welch Hill",
    city: "Novo Cruzeiro",
    zip_code: "39820-000",
    state: null,
    country: "Brazil",
  },
  {
    street_address: "01675 Stoughton Way",
    city: "Sydney",
    zip_code: "1043",
    state: "New South Wales",
    country: "Australia",
  },
  {
    street_address: "69905 Green Ridge Road",
    city: "Adelaide Mail Centre",
    zip_code: "5869",
    state: "South Australia",
    country: "Australia",
  },
  {
    street_address: "606 Oak Center",
    city: "Adelaide Mail Centre",
    zip_code: "5874",
    state: "South Australia",
    country: "Australia",
  },
  {
    street_address: "40497 Mosinee Parkway",
    city: "Sydney",
    zip_code: "1181",
    state: "New South Wales",
    country: "Australia",
  },
  {
    street_address: "5 Northview Avenue",
    city: "Adelaide Mail Centre",
    zip_code: "5874",
    state: "South Australia",
    country: "Australia",
  },
  {
    street_address: "001 Twin Pines Way",
    city: "Granada",
    zip_code: "18005",
    state: "Andalucia",
    country: "Spain",
  },
  {
    street_address: "5139 Schlimgen Park",
    city: "Vigo",
    zip_code: "36210",
    state: "Galicia",
    country: "Spain",
  },
  {
    street_address: "9865 Dexter Road",
    city: "Sant Cugat Del Valles",
    zip_code: "08190",
    state: "Cataluna",
    country: "Spain",
  },
  {
    street_address: "3464 6th Trail",
    city: "Castellon De La Plana/Castello De La Pla",
    zip_code: "12005",
    state: "Comunidad Valenciana",
    country: "Spain",
  },
  {
    street_address: "66 Upham Trail",
    city: "Palencia",
    zip_code: "34005",
    state: "Castilla - Leon",
    country: "Spain",
  },
  {
    street_address: "6 Corscot Drive",
    city: "Muzayri‘",
    zip_code: null,
    state: null,
    country: "United Arab Emirates",
  },
  {
    street_address: "959 Debs Court",
    city: "Adh Dhayd",
    zip_code: null,
    state: null,
    country: "United Arab Emirates",
  },
  {
    street_address: "88 Colorado Court",
    city: "Sharjah",
    zip_code: null,
    state: null,
    country: "United Arab Emirates",
  },
  {
    street_address: "727 Cottonwood Road",
    city: "Dubai",
    zip_code: null,
    state: null,
    country: "United Arab Emirates",
  },
  {
    street_address: "5255 Rowland Alley",
    city: "Al Fujayrah",
    zip_code: null,
    state: null,
    country: "United Arab Emirates",
  },
];

module.exports = addresses;
