const companies = [
  "Wal-Mart",
  "Exxon Mobil",
  "Chevron",
  "Berkshire Hathaway",
  "Apple",
  "Phillips 66",
  "General Motors",
  "Ford Motor",
  "General Electric",
  "Linkedin",
  "AT&T",
  "CVS Caremark",
  "Fannie Mae",
  "UnitedHealth Group",
  "McKesson",
  "Verizon Communications",
  "Hewlett-Packard",
  "J.P. Morgan Chase & Co.",
  "Costco Wholesale",
  "Express Scripts Holding",
  "Bank of America",
  "Cardinal Health",
  "International Business Machines",
  "Kroger",
  "Marathon Petroleum",
  "Citigroup",
  "Archer Daniels Midland",
  "AmerisourceBergen",
  "Wells Fargo",
  "Boeing",
  "Procter & Gamble",
  "Freddie Mac",
  "Home Depot",
  "Microsoft",
  "Amazon.com",
  "Target",
  "Walgreen Co.",
  "WellPoint",
  "Johnson & Johnson",
  "American International Group",
  "State Farm Insurance Cos.",
  "MetLife",
  "PepsiCo",
  "Comcast",
  "United Technologies",
  "Google",
  "ConocoPhillips",
  "Dow Chemical",
  "Caterpillar",
  "Box",
  "Pfizer",
  "Lowe’s Companies",
  "Intel Corporation",
  "Energy Transfer Equity, L.P.",
  "Cisco Systems, Inc.",
  "Enterprise Products Partners L.P.",
  "Aetna Inc.",
  "The Coca-Cola Company",
  "Lockheed Martin Corporation",
  "Best Buy Co., Inc.",
  "The Walt Disney Company",
  "CHS Inc.",
  "Sysco Corporation",
  "FedEx Corporation",
  "Merck & Co., Inc.",
  "INTL FCStone Inc.",
  "Safeway Inc.",
  "Johnson Controls, Inc.",
  "Ingram Micro Inc.",
  "Plains GP Holdings, L.P.",
  "World Fuel Services Corporation",
  "Prudential Financial, Inc.",
  "Humana Inc.",
  "The Goldman Sachs Group, Inc.",
  "Tesoro Corporation",
  "Liberty Mutual Holding Company Inc.",
  "Honeywell International Inc.",
  "United Continental Holdings, Inc.",
  "HCA Holdings, Inc.",
  "Deere & Company",
  "Delta Air Lines, Inc.",
  "Oracle Corporation",
  "Morgan Stanley",
  "Method",
];

module.exports = companies;
