export default {
  accountList: [
    {
      id: 0,
      name: "Wal-Mart",
      contact: {
        name: "Alexa Rogahn",
        phone: "448-782-7756",
        email: "karolann11@gmail.com",
        title: "Trimmer",
      },
      address: {
        street_address: "14302 Messerschmidt Way",
        city: "Columbus",
        zip_code: "31998",
        state: "Georgia",
        country: "United States",
      },
      website: "www.wal-mart.com",
      phone: "258-733-4119",
      stage: "Lead",
      fax: "537-639-6408",
      territory: "NAMER",
      industry: "Security & Investigations",
      licopage: "www.linkedin.com/company/wal-mart/about",
      employee_range: "1001-5000",
    },
    {
      id: 1,
      name: "Exxon Mobil",
      contact: {
        name: "Queen Lueilwitz",
        phone: "798-575-0062",
        email: "ayden.veum42@yahoo.com",
        title: "Film And Video Editor",
      },
      address: {
        street_address: "3 Petterle Terrace",
        city: "Houston",
        zip_code: "77281",
        state: "Texas",
        country: "United States",
      },
      website: "www.exxonmobil.com",
      phone: "801-688-0327",
      stage: "Sold",
      fax: "785-772-4544",
      territory: "NAMER",
      industry: "Leisure & Travel",
      licopage: "www.linkedin.com/company/exxonmobil/about",
      employee_range: "Self-employed",
    },
    {
      id: 2,
      name: "Chevron",
      contact: {
        name: "Armani Gleason",
        phone: "759-311-8492",
        email: "carmela_harber35@hotmail.com",
        title: "Pharmacy Aide",
      },
      address: {
        street_address: "17 Thierer Drive",
        city: "Winston Salem",
        zip_code: "27150",
        state: "North Carolina",
        country: "United States",
      },
      website: "www.chevron.com",
      phone: "381-908-3229",
      stage: "Not Interested",
      fax: "659-441-9226",
      territory: "NAMER",
      industry: "Security & Investigations",
      licopage: "www.linkedin.com/company/chevron/about",
      employee_range: "51-200",
    },
    {
      id: 3,
      name: "Berkshire Hathaway",
      contact: {
        name: "Manley Huels",
        phone: "212-591-5923",
        email: "jeramy_kutch51@gmail.com",
        title: "Biochemist",
      },
      address: {
        street_address: "84 Mariners Cove Parkway",
        city: "Philadelphia",
        zip_code: "19191",
        state: "Pennsylvania",
        country: "United States",
      },
      website: "www.berkshirehathaway.com",
      phone: "475-282-7988",
      stage: "Not Interested",
      fax: "240-747-2927",
      territory: "NAMER",
      industry: "Consumer Services",
      licopage: "www.linkedin.com/company/berkshirehathaway/about",
      employee_range: "1001-5000",
    },
    {
      id: 4,
      name: "Apple",
      contact: {
        name: "Lon Bernier",
        phone: "418-536-2406",
        email: "salvatore.frami@gmail.com",
        title: "Motorboat Mechanic",
      },
      address: {
        street_address: "9403 Londonderry Street",
        city: "Cincinnati",
        zip_code: "45208",
        state: "Ohio",
        country: "United States",
      },
      website: "www.apple.com",
      phone: "266-612-3029",
      stage: "Lead",
      fax: "496-957-7010",
      territory: "NAMER",
      industry: "Performing Arts",
      licopage: "www.linkedin.com/company/apple/about",
      employee_range: "1-10",
    },
    {
      id: 5,
      name: "Phillips 66",
      contact: {
        name: "Adrianna Johnston",
        phone: "672-344-3592",
        email: "patience_mraz@yahoo.com",
        title: "Animator",
      },
      address: {
        street_address: "10079 Glendale Center",
        city: "Minneapolis",
        zip_code: "55417",
        state: "Minnesota",
        country: "United States",
      },
      website: "www.phillips66.com",
      phone: "233-759-0725",
      stage: "Not Interested",
      fax: "838-511-2601",
      territory: "NAMER",
      industry: "Media Production",
      licopage: "www.linkedin.com/company/phillips66/about",
      employee_range: "11-50",
    },
    {
      id: 6,
      name: "General Motors",
      contact: {
        name: "Brannon O'Conner",
        phone: "410-990-8217",
        email: "kolby_ohara@yahoo.com",
        title: "Hearing Officer",
      },
      address: {
        street_address: "15593 Lakewood Gardens Park",
        city: "Warren",
        zip_code: "44485",
        state: "Ohio",
        country: "United States",
      },
      website: "www.generalmotors.com",
      phone: "783-688-3674",
      stage: "Not Interested",
      fax: "354-275-5225",
      territory: "NAMER",
      industry: "Accounting",
      licopage: "www.linkedin.com/company/generalmotors/about",
      employee_range: "501-1000",
    },
    {
      id: 7,
      name: "Ford Motor",
      contact: {
        name: "Heather Bins",
        phone: "565-975-4056",
        email: "maximillia72@gmail.com",
        title: "Optician",
      },
      address: {
        street_address: "544 Petterle Pass",
        city: "Waco",
        zip_code: "76796",
        state: "Texas",
        country: "United States",
      },
      website: "www.fordmotor.com",
      phone: "241-837-9788",
      stage: "Lead",
      fax: "437-492-6450",
      territory: "NAMER",
      industry: "Legislative Office",
      licopage: "www.linkedin.com/company/fordmotor/about",
      employee_range: "201-500",
    },
    {
      id: 8,
      name: "General Electric",
      contact: {
        name: "Nicolas Hudson",
        phone: "267-292-8691",
        email: "davonte_nicolas85@hotmail.com",
        title: "Radio Equipment Installer",
      },
      address: {
        street_address: "62 3rd Court",
        city: "Cincinnati",
        zip_code: "45228",
        state: "Ohio",
        country: "United States",
      },
      website: "www.generalelectric.com",
      phone: "302-408-5165",
      stage: "Lead",
      fax: "521-991-6682",
      territory: "NAMER",
      industry: "Education Management",
      licopage: "www.linkedin.com/company/generalelectric/about",
      employee_range: "501-1000",
    },
    {
      id: 9,
      name: "Linkedin",
      contact: {
        name: "Alexandrine Hand",
        phone: "973-284-3579",
        email: "bradley_schroeder77@yahoo.com",
        title: "Heating Installer",
      },
      address: {
        street_address: "7379 Thompson Place",
        city: "Tacoma",
        zip_code: "98405",
        state: "Washington",
        country: "United States",
      },
      website: "www.linkedin.com",
      phone: "920-928-8873",
      stage: "Lead",
      fax: "664-457-9160",
      territory: "NAMER",
      industry: "Sporting Goods",
      licopage: "www.linkedin.com/company/linkedin/about",
      employee_range: "11-50",
    },
    {
      id: 10,
      name: "AT&T",
      contact: {
        name: "Celestino Carroll",
        phone: "291-715-9250",
        email: "santiago45@gmail.com",
        title: "Engineer",
      },
      address: {
        street_address: "50 Northport Road",
        city: "Singapore",
        zip_code: null,
        state: null,
        country: "Singapore",
      },
      website: "www.at&t.com",
      phone: "907-285-9452",
      stage: "Sold",
      fax: "545-383-5084",
      territory: "APAC",
      industry: "Pharmaceuticals",
      licopage: "www.linkedin.com/company/at&t/about",
      employee_range: "51-200",
    },
    {
      id: 11,
      name: "CVS Caremark",
      contact: {
        name: "Alexys Sauer",
        phone: "357-804-7031",
        email: "lourdes.quitzon11@gmail.com",
        title: "Animal Trainer",
      },
      address: {
        street_address: "8 Sauthoff Plaza",
        city: "Singapore",
        zip_code: null,
        state: null,
        country: "Singapore",
      },
      website: "www.cvscaremark.com",
      phone: "492-308-1566",
      stage: "Not Interested",
      fax: "736-932-5352",
      territory: "APAC",
      industry: "Public Safety",
      licopage: "www.linkedin.com/company/cvscaremark/about",
      employee_range: "10,001+",
    },
    {
      id: 12,
      name: "Fannie Mae",
      contact: {
        name: "Doug Nicolas",
        phone: "517-816-3186",
        email: "herminio_ruecker97@yahoo.com",
        title: "Mental Health Counselor",
      },
      address: {
        street_address: "5 Golf View Parkway",
        city: "Singapore",
        zip_code: null,
        state: null,
        country: "Singapore",
      },
      website: "www.fanniemae.com",
      phone: "468-880-0895",
      stage: "Not Interested",
      fax: "796-598-0948",
      territory: "APAC",
      industry: "Writing & Editing",
      licopage: "www.linkedin.com/company/fanniemae/about",
      employee_range: "5001-10,000",
    },
    {
      id: 13,
      name: "UnitedHealth Group",
      contact: {
        name: "Wyatt Rogahn",
        phone: "503-842-9960",
        email: "dena34@yahoo.com",
        title: "Signal Repairer",
      },
      address: {
        street_address: "4 Sycamore Pass",
        city: "Singapore",
        zip_code: null,
        state: null,
        country: "Singapore",
      },
      website: "www.unitedhealthgroup.com",
      phone: "903-868-0069",
      stage: "Lead",
      fax: "241-414-5919",
      territory: "APAC",
      industry: "Wine & Spirits",
      licopage: "www.linkedin.com/company/unitedhealthgroup/about",
      employee_range: "1001-5000",
    },
    {
      id: 14,
      name: "McKesson",
      contact: {
        name: "Ford Kulas",
        phone: "916-304-0286",
        email: "lauryn65@hotmail.com",
        title: "Fire Investigator",
      },
      address: {
        street_address: "54208 Trailsway Crossing",
        city: "Singapore",
        zip_code: null,
        state: null,
        country: "Singapore",
      },
      website: "www.mckesson.com",
      phone: "652-208-4032",
      stage: "Not Interested",
      fax: "764-415-6603",
      territory: "APAC",
      industry: "Events Services",
      licopage: "www.linkedin.com/company/mckesson/about",
      employee_range: "1001-5000",
    },
    {
      id: 15,
      name: "Verizon Communications",
      contact: {
        name: "Marshall Mills",
        phone: "239-370-5355",
        email: "saige99@yahoo.com",
        title: "Coil Finisher",
      },
      address: {
        street_address: "50157 Dennis Road",
        city: "Kashima-shi",
        zip_code: "314-0048",
        state: null,
        country: "Japan",
      },
      website: "www.verizoncommunications.com",
      phone: "984-616-9814",
      stage: "Lead",
      fax: "892-791-4846",
      territory: "APAC",
      industry: "Arts & Crafts",
      licopage: "www.linkedin.com/company/verizoncommunications/about",
      employee_range: "10,001+",
    },
    {
      id: 16,
      name: "Hewlett-Packard",
      contact: {
        name: "Annamae McClure",
        phone: "488-296-6303",
        email: "maurine_weimann@hotmail.com",
        title: "Rental Clerk",
      },
      address: {
        street_address: "104 Buena Vista Plaza",
        city: "Ichinomiya",
        zip_code: "941-0056",
        state: null,
        country: "Japan",
      },
      website: "www.hewlett-packard.com",
      phone: "300-745-8482",
      stage: "Not Interested",
      fax: "623-228-0125",
      territory: "APAC",
      industry: "Legal Services",
      licopage: "www.linkedin.com/company/hewlett-packard/about",
      employee_range: "1001-5000",
    },
    {
      id: 17,
      name: "J.P. Morgan Chase & Co.",
      contact: {
        name: "Reginald Bergnaum",
        phone: "643-522-3117",
        email: "zella_stamm@hotmail.com",
        title: "Earth Driller",
      },
      address: {
        street_address: "40 Prairieview Avenue",
        city: "Tōkamachi",
        zip_code: "949-8612",
        state: null,
        country: "Japan",
      },
      website: "www.j.p.morgan chase & co..com",
      phone: "269-655-9643",
      stage: "Not Interested",
      fax: "266-410-6362",
      territory: "APAC",
      industry: "Individual & Family Services",
      licopage: "www.linkedin.com/company/j.p.morgan chase & co./about",
      employee_range: "10,001+",
    },
    {
      id: 18,
      name: "Costco Wholesale",
      contact: {
        name: "Neva Mohr",
        phone: "474-686-2186",
        email: "jaylan23@hotmail.com",
        title: "Optician",
      },
      address: {
        street_address: "6 Sloan Park",
        city: "Nayoro",
        zip_code: "607-8077",
        state: null,
        country: "Japan",
      },
      website: "www.costcowholesale.com",
      phone: "721-478-8030",
      stage: "Lead",
      fax: "702-601-3817",
      territory: "APAC",
      industry: "Accounting",
      licopage: "www.linkedin.com/company/costcowholesale/about",
      employee_range: "11-50",
    },
    {
      id: 19,
      name: "Express Scripts Holding",
      contact: {
        name: "Ethyl Spencer",
        phone: "564-532-4038",
        email: "akeem.roob@gmail.com",
        title: "Secondary Education Teacher",
      },
      address: {
        street_address: "76 Veith Center",
        city: "Kokubu-matsuki",
        zip_code: "584-0024",
        state: null,
        country: "Japan",
      },
      website: "www.expressscripts holding.com",
      phone: "287-916-7820",
      stage: "Sold",
      fax: "590-938-5178",
      territory: "APAC",
      industry: "Furniture",
      licopage: "www.linkedin.com/company/expressscripts holding/about",
      employee_range: "5001-10,000",
    },
    {
      id: 20,
      name: "Bank of America",
      contact: {
        name: "Merle O'Hara",
        phone: "736-987-9934",
        email: "xander_rau@yahoo.com",
        title: "Flight Attendant",
      },
      address: {
        street_address: "6 Troy Park",
        city: "Peachland",
        zip_code: "B3S",
        state: "British Columbia",
        country: "Canada",
      },
      website: "www.bankof america.com",
      phone: "714-934-4222",
      stage: "Lead",
      fax: "910-561-5066",
      territory: "NAMER",
      industry: "Investment Management",
      licopage: "www.linkedin.com/company/bankof america/about",
      employee_range: "501-1000",
    },
    {
      id: 21,
      name: "Cardinal Health",
      contact: {
        name: "Skyla Lemke",
        phone: "979-312-1705",
        email: "emmett.lehner87@hotmail.com",
        title: "Transportation Inspector",
      },
      address: {
        street_address: "417 Maywood Point",
        city: "Devon",
        zip_code: "T9G",
        state: "Alberta",
        country: "Canada",
      },
      website: "www.cardinalhealth.com",
      phone: "590-474-9947",
      stage: "Not Interested",
      fax: "956-778-3996",
      territory: "NAMER",
      industry: "Executive Office",
      licopage: "www.linkedin.com/company/cardinalhealth/about",
      employee_range: "1-10",
    },
    {
      id: 22,
      name: "International Business Machines",
      contact: {
        name: "Macy Armstrong",
        phone: "984-614-1385",
        email: "gwendolyn_cummerata57@hotmail.com",
        title: "Ski Patrol",
      },
      address: {
        street_address: "7916 Stuart Park",
        city: "Marieville",
        zip_code: "J3M",
        state: "Québec",
        country: "Canada",
      },
      website: "www.internationalbusiness machines.com",
      phone: "958-235-8760",
      stage: "Sold",
      fax: "553-316-7078",
      territory: "NAMER",
      industry: "Education Management",
      licopage: "www.linkedin.com/company/internationalbusiness machines/about",
      employee_range: "1-10",
    },
    {
      id: 23,
      name: "Kroger",
      contact: {
        name: "Roy Hand",
        phone: "396-496-0938",
        email: "isidro2@hotmail.com",
        title: "Adjudicator",
      },
      address: {
        street_address: "5515 Donald Alley",
        city: "Hearst",
        zip_code: "S4A",
        state: "Ontario",
        country: "Canada",
      },
      website: "www.kroger.com",
      phone: "261-557-9166",
      stage: "Not Interested",
      fax: "866-396-6184",
      territory: "NAMER",
      industry: "Outsourcing/Offshoring",
      licopage: "www.linkedin.com/company/kroger/about",
      employee_range: "1001-5000",
    },
    {
      id: 24,
      name: "Marathon Petroleum",
      contact: {
        name: "Chloe Bailey",
        phone: "535-612-4895",
        email: "monique_von@hotmail.com",
        title: "Athlete",
      },
      address: {
        street_address: "17888 Meadow Ridge Center",
        city: "Kitimat",
        zip_code: "V8C",
        state: "British Columbia",
        country: "Canada",
      },
      website: "www.marathonpetroleum.com",
      phone: "670-640-4738",
      stage: "Not Interested",
      fax: "225-328-2697",
      territory: "NAMER",
      industry: "Research",
      licopage: "www.linkedin.com/company/marathonpetroleum/about",
      employee_range: "1-10",
    },
    {
      id: 25,
      name: "Citigroup",
      contact: {
        name: "Maynard Gislason",
        phone: "587-865-8449",
        email: "frankie.wisozk@gmail.com",
        title: "History Teacher",
      },
      address: {
        street_address: "1545 Homewood Pass",
        city: "Emiliano Zapata",
        zip_code: "48892",
        state: "Jalisco",
        country: "Mexico",
      },
      website: "www.citigroup.com",
      phone: "259-282-6849",
      stage: "Sold",
      fax: "267-405-1672",
      territory: "NAMER",
      industry: "Computer Hardware",
      licopage: "www.linkedin.com/company/citigroup/about",
      employee_range: "5001-10,000",
    },
    {
      id: 26,
      name: "Archer Daniels Midland",
      contact: {
        name: "Hayley Greenholt",
        phone: "379-918-2530",
        email: "ruthe_lockman25@hotmail.com",
        title: "Telemarketer",
      },
      address: {
        street_address: "0048 Knutson Point",
        city: "Lindavista",
        zip_code: "29557",
        state: "Chiapas",
        country: "Mexico",
      },
      website: "www.archerdaniels midland.com",
      phone: "539-494-6319",
      stage: "Not Interested",
      fax: "774-508-2949",
      territory: "NAMER",
      industry: "Industrial Automation",
      licopage: "www.linkedin.com/company/archerdaniels midland/about",
      employee_range: "5001-10,000",
    },
    {
      id: 27,
      name: "AmerisourceBergen",
      contact: {
        name: "Jordon Douglas",
        phone: "662-689-9259",
        email: "godfrey1@hotmail.com",
        title: "Production Occupation",
      },
      address: {
        street_address: "19 Manufacturers Lane",
        city: "Santa Rosa",
        zip_code: "67803",
        state: "Nuevo Leon",
        country: "Mexico",
      },
      website: "www.amerisourcebergen.com",
      phone: "302-702-9599",
      stage: "Not Interested",
      fax: "313-675-0383",
      territory: "NAMER",
      industry: "Higher Education",
      licopage: "www.linkedin.com/company/amerisourcebergen/about",
      employee_range: "1001-5000",
    },
    {
      id: 28,
      name: "Wells Fargo",
      contact: {
        name: "Vicente Wyman",
        phone: "679-912-9840",
        email: "twila.mcdermott@hotmail.com",
        title: "Coin Machine Servicer",
      },
      address: {
        street_address: "38872 Talisman Street",
        city: "Benito Juarez",
        zip_code: "66410",
        state: "Nuevo Leon",
        country: "Mexico",
      },
      website: "www.wellsfargo.com",
      phone: "686-342-5930",
      stage: "Sold",
      fax: "797-332-2775",
      territory: "NAMER",
      industry: "Tobacco",
      licopage: "www.linkedin.com/company/wellsfargo/about",
      employee_range: "501-1000",
    },
    {
      id: 29,
      name: "Boeing",
      contact: {
        name: "Darrion Franecki",
        phone: "667-897-2968",
        email: "melyna_dare@hotmail.com",
        title: "Railroad Conductor",
      },
      address: {
        street_address: "521 Michigan Street",
        city: "Emiliano Zapata",
        zip_code: "70805",
        state: "Oaxaca",
        country: "Mexico",
      },
      website: "www.boeing.com",
      phone: "212-841-2405",
      stage: "Sold",
      fax: "881-676-2344",
      territory: "NAMER",
      industry: "Business Supplies & Equipment",
      licopage: "www.linkedin.com/company/boeing/about",
      employee_range: "1-10",
    },
    {
      id: 30,
      name: "Procter & Gamble",
      contact: {
        name: "Marisol Treutel",
        phone: "656-540-3675",
        email: "audie.koepp81@hotmail.com",
        title: "Concrete Finisher",
      },
      address: {
        street_address: "5 Eastlawn Pass",
        city: "Capitão Poço",
        zip_code: "68650-000",
        state: null,
        country: "Brazil",
      },
      website: "www.procter& gamble.com",
      phone: "530-711-2835",
      stage: "Lead",
      fax: "301-278-0978",
      territory: "NAMER",
      industry: "Performing Arts",
      licopage: "www.linkedin.com/company/procter& gamble/about",
      employee_range: "10,001+",
    },
    {
      id: 31,
      name: "Freddie Mac",
      contact: {
        name: "Destini Collins",
        phone: "881-619-1929",
        email: "edythe.stiedemann@gmail.com",
        title: "Fish And Game Warden",
      },
      address: {
        street_address: "6 Rusk Way",
        city: "Boa Esperança",
        zip_code: "87390-000",
        state: null,
        country: "Brazil",
      },
      website: "www.freddiemac.com",
      phone: "740-645-2661",
      stage: "Lead",
      fax: "968-340-6652",
      territory: "NAMER",
      industry: "Accounting",
      licopage: "www.linkedin.com/company/freddiemac/about",
      employee_range: "1001-5000",
    },
    {
      id: 32,
      name: "Home Depot",
      contact: {
        name: "Aliza Lynch",
        phone: "440-698-4456",
        email: "cale59@yahoo.com",
        title: "Landscape Architect",
      },
      address: {
        street_address: "6887 Truax Crossing",
        city: "Itatinga",
        zip_code: "18690-000",
        state: null,
        country: "Brazil",
      },
      website: "www.homedepot.com",
      phone: "894-643-6709",
      stage: "Sold",
      fax: "857-594-5716",
      territory: "NAMER",
      industry: "Political Organization",
      licopage: "www.linkedin.com/company/homedepot/about",
      employee_range: "11-50",
    },
    {
      id: 33,
      name: "Microsoft",
      contact: {
        name: "Dashawn Feeney",
        phone: "634-591-9929",
        email: "gabrielle_cormier77@yahoo.com",
        title: "Blending Machine Operator",
      },
      address: {
        street_address: "48727 Morningstar Trail",
        city: "Quirinópolis",
        zip_code: "75860-000",
        state: null,
        country: "Brazil",
      },
      website: "www.microsoft.com",
      phone: "361-732-5202",
      stage: "Not Interested",
      fax: "962-850-8091",
      territory: "NAMER",
      industry: "Information Services",
      licopage: "www.linkedin.com/company/microsoft/about",
      employee_range: "1001-5000",
    },
    {
      id: 34,
      name: "Amazon.com",
      contact: {
        name: "Jannie Mayer",
        phone: "708-437-4845",
        email: "kelsie_steuber57@hotmail.com",
        title: "Makeup Artist",
      },
      address: {
        street_address: "1063 Welch Hill",
        city: "Novo Cruzeiro",
        zip_code: "39820-000",
        state: null,
        country: "Brazil",
      },
      website: "www.amazon.com.com",
      phone: "361-434-9018",
      stage: "Not Interested",
      fax: "906-390-2840",
      territory: "NAMER",
      industry: "Public Safety",
      licopage: "www.linkedin.com/company/amazon.com/about",
      employee_range: "51-200",
    },
    {
      id: 35,
      name: "Target",
      contact: {
        name: "Austyn Adams",
        phone: "537-988-6823",
        email: "roderick.miller@hotmail.com",
        title: "Fire Investigator",
      },
      address: {
        street_address: "01675 Stoughton Way",
        city: "Sydney",
        zip_code: "1043",
        state: "New South Wales",
        country: "Australia",
      },
      website: "www.target.com",
      phone: "447-907-4969",
      stage: "Lead",
      fax: "678-606-4261",
      territory: "APAC",
      industry: "Market Research",
      licopage: "www.linkedin.com/company/target/about",
      employee_range: "5001-10,000",
    },
    {
      id: 36,
      name: "Walgreen Co.",
      contact: {
        name: "Javon Little",
        phone: "460-662-5257",
        email: "reagan.dare72@hotmail.com",
        title: "Conciliator",
      },
      address: {
        street_address: "69905 Green Ridge Road",
        city: "Adelaide Mail Centre",
        zip_code: "5869",
        state: "South Australia",
        country: "Australia",
      },
      website: "www.walgreenco..com",
      phone: "485-257-7665",
      stage: "Lead",
      fax: "569-870-9998",
      territory: "APAC",
      industry: "Business Supplies & Equipment",
      licopage: "www.linkedin.com/company/walgreenco./about",
      employee_range: "5001-10,000",
    },
    {
      id: 37,
      name: "WellPoint",
      contact: {
        name: "Maximus Gusikowski",
        phone: "656-805-4288",
        email: "tiara71@yahoo.com",
        title: "Social Science Research Assistant",
      },
      address: {
        street_address: "606 Oak Center",
        city: "Adelaide Mail Centre",
        zip_code: "5874",
        state: "South Australia",
        country: "Australia",
      },
      website: "www.wellpoint.com",
      phone: "399-790-3411",
      stage: "Lead",
      fax: "381-262-0189",
      territory: "APAC",
      industry: "Fine Art",
      licopage: "www.linkedin.com/company/wellpoint/about",
      employee_range: "11-50",
    },
    {
      id: 38,
      name: "Johnson & Johnson",
      contact: {
        name: "Sedrick Johnson",
        phone: "844-390-0034",
        email: "lorna.schaden@gmail.com",
        title: "Political Scientist",
      },
      address: {
        street_address: "40497 Mosinee Parkway",
        city: "Sydney",
        zip_code: "1181",
        state: "New South Wales",
        country: "Australia",
      },
      website: "www.johnson& johnson.com",
      phone: "686-894-9799",
      stage: "Lead",
      fax: "365-439-3817",
      territory: "APAC",
      industry: "Events Services",
      licopage: "www.linkedin.com/company/johnson& johnson/about",
      employee_range: "51-200",
    },
    {
      id: 39,
      name: "American International Group",
      contact: {
        name: "Francesca Gerhold",
        phone: "641-457-9288",
        email: "elliot.kling@yahoo.com",
        title: "Legal Assistant",
      },
      address: {
        street_address: "5 Northview Avenue",
        city: "Adelaide Mail Centre",
        zip_code: "5874",
        state: "South Australia",
        country: "Australia",
      },
      website: "www.americaninternational group.com",
      phone: "796-380-5423",
      stage: "Not Interested",
      fax: "437-512-1040",
      territory: "APAC",
      industry: "Music",
      licopage: "www.linkedin.com/company/americaninternational group/about",
      employee_range: "Self-employed",
    },
    {
      id: 40,
      name: "State Farm Insurance Cos.",
      contact: {
        name: "Bradley Dare",
        phone: "948-441-3665",
        email: "alexandria.heller@hotmail.com",
        title: "Sewer Pipe Cleaner",
      },
      address: {
        street_address: "001 Twin Pines Way",
        city: "Granada",
        zip_code: "18005",
        state: "Andalucia",
        country: "Spain",
      },
      website: "www.statefarm insurance cos..com",
      phone: "396-307-9096",
      stage: "Not Interested",
      fax: "657-757-6228",
      territory: "EMEA",
      industry: "Alternative Dispute Resolution",
      licopage: "www.linkedin.com/company/statefarm insurance cos./about",
      employee_range: "201-500",
    },
    {
      id: 41,
      name: "MetLife",
      contact: {
        name: "Johnathan Kling",
        phone: "977-416-6255",
        email: "cordell.prosacco@hotmail.com",
        title: "Animal Scientist",
      },
      address: {
        street_address: "5139 Schlimgen Park",
        city: "Vigo",
        zip_code: "36210",
        state: "Galicia",
        country: "Spain",
      },
      website: "www.metlife.com",
      phone: "254-663-3291",
      stage: "Sold",
      fax: "248-794-1358",
      territory: "EMEA",
      industry: "Animation",
      licopage: "www.linkedin.com/company/metlife/about",
      employee_range: "201-500",
    },
    {
      id: 42,
      name: "PepsiCo",
      contact: {
        name: "Sydni Crooks",
        phone: "271-909-4336",
        email: "erik_vonrueden12@gmail.com",
        title: "Chemist",
      },
      address: {
        street_address: "9865 Dexter Road",
        city: "Sant Cugat Del Valles",
        zip_code: "08190",
        state: "Cataluna",
        country: "Spain",
      },
      website: "www.pepsico.com",
      phone: "323-289-3799",
      stage: "Lead",
      fax: "839-415-7928",
      territory: "EMEA",
      industry: "Philanthropy",
      licopage: "www.linkedin.com/company/pepsico/about",
      employee_range: "501-1000",
    },
    {
      id: 43,
      name: "Comcast",
      contact: {
        name: "Ned Thiel",
        phone: "372-963-7499",
        email: "cullen_kirlin@hotmail.com",
        title: "Prosthetist",
      },
      address: {
        street_address: "3464 6th Trail",
        city: "Castellon De La Plana/Castello De La Pla",
        zip_code: "12005",
        state: "Comunidad Valenciana",
        country: "Spain",
      },
      website: "www.comcast.com",
      phone: "770-494-1370",
      stage: "Lead",
      fax: "460-647-2707",
      territory: "EMEA",
      industry: "Mechanical or Industrial Engineering",
      licopage: "www.linkedin.com/company/comcast/about",
      employee_range: "201-500",
    },
    {
      id: 44,
      name: "United Technologies",
      contact: {
        name: "Guadalupe Beahan",
        phone: "411-772-2737",
        email: "sierra_kuhn@gmail.com",
        title: "Heating Mechanic",
      },
      address: {
        street_address: "66 Upham Trail",
        city: "Palencia",
        zip_code: "34005",
        state: "Castilla - Leon",
        country: "Spain",
      },
      website: "www.unitedtechnologies.com",
      phone: "312-506-3156",
      stage: "Not Interested",
      fax: "903-547-5520",
      territory: "EMEA",
      industry: "Outsourcing/Offshoring",
      licopage: "www.linkedin.com/company/unitedtechnologies/about",
      employee_range: "201-500",
    },
    {
      id: 45,
      name: "Google",
      contact: {
        name: "Evelyn Bernhard",
        phone: "607-789-0059",
        email: "raphaelle_blanda90@yahoo.com",
        title: "Sales Representative",
      },
      address: {
        street_address: "6 Corscot Drive",
        city: "Muzayri‘",
        zip_code: null,
        state: null,
        country: "United Arab Emirates",
      },
      website: "www.google.com",
      phone: "693-798-8144",
      stage: "Sold",
      fax: "848-321-1862",
      territory: "EMEA",
      industry: "Glass, Ceramics & Concrete",
      licopage: "www.linkedin.com/company/google/about",
      employee_range: "501-1000",
    },
    {
      id: 46,
      name: "ConocoPhillips",
      contact: {
        name: "Jabari Kutch",
        phone: "565-935-5994",
        email: "zelda_pfannerstill@hotmail.com",
        title: "Structural Metal Fabricator",
      },
      address: {
        street_address: "959 Debs Court",
        city: "Adh Dhayd",
        zip_code: null,
        state: null,
        country: "United Arab Emirates",
      },
      website: "www.conocophillips.com",
      phone: "522-813-5399",
      stage: "Lead",
      fax: "378-635-9206",
      territory: "EMEA",
      industry: "Chemicals",
      licopage: "www.linkedin.com/company/conocophillips/about",
      employee_range: "51-200",
    },
    {
      id: 47,
      name: "Dow Chemical",
      contact: {
        name: "Dedrick Kuphal",
        phone: "509-523-1786",
        email: "larue5@hotmail.com",
        title: "Maxillofacial Surgeon",
      },
      address: {
        street_address: "88 Colorado Court",
        city: "Sharjah",
        zip_code: null,
        state: null,
        country: "United Arab Emirates",
      },
      website: "www.dowchemical.com",
      phone: "598-974-0229",
      stage: "Sold",
      fax: "319-759-2259",
      territory: "EMEA",
      industry: "Tobacco",
      licopage: "www.linkedin.com/company/dowchemical/about",
      employee_range: "1-10",
    },
    {
      id: 48,
      name: "Caterpillar",
      contact: {
        name: "Raul Ferry",
        phone: "798-831-2571",
        email: "stephanie.huel@gmail.com",
        title: "Mechanical Drafter",
      },
      address: {
        street_address: "727 Cottonwood Road",
        city: "Dubai",
        zip_code: null,
        state: null,
        country: "United Arab Emirates",
      },
      website: "www.caterpillar.com",
      phone: "853-976-7787",
      stage: "Not Interested",
      fax: "897-983-5269",
      territory: "EMEA",
      industry: "Environmental Services",
      licopage: "www.linkedin.com/company/caterpillar/about",
      employee_range: "201-500",
    },
    {
      id: 49,
      name: "Box",
      contact: {
        name: "Karine Sporer",
        phone: "775-755-1687",
        email: "dino_rempel86@gmail.com",
        title: "Agricultural Technician",
      },
      address: {
        street_address: "5255 Rowland Alley",
        city: "Al Fujayrah",
        zip_code: null,
        state: null,
        country: "United Arab Emirates",
      },
      website: "www.box.com",
      phone: "659-773-3285",
      stage: "Not Interested",
      fax: "943-757-8915",
      territory: "EMEA",
      industry: "Chemicals",
      licopage: "www.linkedin.com/company/box/about",
      employee_range: "201-500",
    },
  ],
};
