export default {
  accountList: [
    {
      id: 0,
      name: "Wal-Mart",
      contact: {
        name: "Lelah Pfeffer",
        phone: "782.760.8553",
        email: "Dewitt_Hartmann@yahoo.com",
        title: "molder",
      },
      website: "www.wal-mart.com",
      phone: "(994) 591-8979 x4267",
      stage: "Not Interested",
      fax: "(324) 457-5648",
      country: "Burkina Faso",
      territory: "EMEA",
      industry: "Sports",
      licopage: "www.linkedin.com/company/wal-mart/about",
      employee_range: "10,001+",
    },
    {
      id: 1,
      name: "Exxon Mobil",
      contact: {
        name: "Morgan O'Kon",
        phone: "1-609-203-5244 x2766",
        email: "Hilbert.Kuhn@hotmail.com",
        title: "composer",
      },
      website: "www.exxonundefinedmobil.com",
      phone: "1-380-454-4293 x683",
      stage: "Not Interested",
      fax: "(205) 647-9168",
      country: "Djibouti",
      territory: "EMEA",
      industry: "Civic & Social Organization",
      licopage: "www.linkedin.com/company/exxonundefinedmobil/about",
      employee_range: "201-500",
    },
    {
      id: 2,
      name: "Chevron",
      contact: {
        name: "Oral Jenkins",
        phone: "(749) 415-5944 x72924",
        email: "Elmira58@gmail.com",
        title: "umpire",
      },
      website: "www.chevron.com",
      phone: "(949) 445-1054",
      stage: "Lead",
      fax: "301-660-7900 x72353",
      country: "Saint Helena",
      territory: "EMEA",
      industry: "Veterinary",
      licopage: "www.linkedin.com/company/chevron/about",
      employee_range: "501-1000",
    },
    {
      id: 3,
      name: "Berkshire Hathaway",
      contact: {
        name: "Danielle Osinski",
        phone: "(494) 911-2859",
        email: "Celestine.White60@gmail.com",
        title: "computer operator",
      },
      website: "www.berkshireundefinedhathaway.com",
      phone: "465.754.3239 x66247",
      stage: "Sold",
      fax: "451-874-2927 x4022",
      country: "French Guiana",
      territory: "NAMER",
      industry: "Newspapers",
      licopage: "www.linkedin.com/company/berkshireundefinedhathaway/about",
      employee_range: "501-1000",
    },
    {
      id: 4,
      name: "Apple",
      contact: {
        name: "Humberto Fritsch",
        phone: "(391) 877-8987",
        email: "Marques_Goldner44@yahoo.com",
        title: "rock splitter",
      },
      website: "www.apple.com",
      phone: "(509) 971-6909 x726",
      stage: "Lead",
      fax: "1-969-707-5032",
      country: "Iceland",
      territory: "EMEA",
      industry: "Professional Training",
      licopage: "www.linkedin.com/company/apple/about",
      employee_range: "11-50",
    },
    {
      id: 5,
      name: "Phillips 66",
      contact: {
        name: "Natalia Kuhic",
        phone: "(592) 361-0400 x4341",
        email: "Sheila.Wehner57@hotmail.com",
        title: "space scientist",
      },
      website: "www.phillipsundefined66.com",
      phone: "232.701.2047 x80854",
      stage: "Not Interested",
      fax: "(747) 807-9578 x8655",
      country: "Jordan",
      territory: "EMEA",
      industry: "Fundraising",
      licopage: "www.linkedin.com/company/phillipsundefined66/about",
      employee_range: "1-10",
    },
    {
      id: 6,
      name: "General Motors",
      contact: {
        name: "Melyssa Ritchie",
        phone: "(876) 679-8362 x23986",
        email: "Asa.Prohaska26@gmail.com",
        title: "model",
      },
      website: "www.generalundefinedmotors.com",
      phone: "1-868-371-3183 x044",
      stage: "Not Interested",
      fax: "(578) 777-0099",
      country: "Saint Martin",
      territory: "NAMER",
      industry: "Judiciary",
      licopage: "www.linkedin.com/company/generalundefinedmotors/about",
      employee_range: "5001-10,000",
    },
    {
      id: 7,
      name: "Ford Motor",
      contact: {
        name: "Roger Weber",
        phone: "670-309-9394 x694",
        email: "Destinee.Witting90@hotmail.com",
        title: "history teacher",
      },
      website: "www.fordundefinedmotor.com",
      phone: "(466) 284-9063",
      stage: "Not Interested",
      fax: "(780) 392-1757 x9492",
      country: "Liechtenstein",
      territory: "EMEA",
      industry: "Medical Practice",
      licopage: "www.linkedin.com/company/fordundefinedmotor/about",
      employee_range: "5001-10,000",
    },
    {
      id: 8,
      name: "General Electric",
      contact: {
        name: "Raegan Goodwin",
        phone: "571-927-4726",
        email: "Roberto.VonRueden95@hotmail.com",
        title: "tool filer",
      },
      website: "www.generalundefinedelectric.com",
      phone: "(972) 384-2644 x7528",
      stage: "Not Interested",
      fax: "1-535-749-2046 x0883",
      country: "Chile",
      territory: "NAMER",
      industry: "International Affairs",
      licopage: "www.linkedin.com/company/generalundefinedelectric/about",
      employee_range: "1001-5000",
    },
    {
      id: 9,
      name: "Linkedin",
      contact: {
        name: "Alyce VonRueden",
        phone: "553.645.4685",
        email: "Kenneth_Tillman78@yahoo.com",
        title: "nuclear power reactor operator",
      },
      website: "www.linkedin.com",
      phone: "389-497-9681",
      stage: "Sold",
      fax: "1-366-205-0614",
      country: "Albania",
      territory: "EMEA",
      industry: "Machinery",
      licopage: "www.linkedin.com/company/linkedin/about",
      employee_range: "51-200",
    },
    {
      id: 10,
      name: "AT&T",
      contact: {
        name: "Ryley Nienow",
        phone: "814.643.9323 x0506",
        email: "Cristal.Ankunding64@hotmail.com",
        title: "roof bolter",
      },
      website: "www.at&t.com",
      phone: "1-723-957-5810 x123",
      stage: "Sold",
      fax: "(221) 645-1234 x2537",
      country: "Italy",
      territory: "EMEA",
      industry: "Accounting",
      licopage: "www.linkedin.com/company/at&t/about",
      employee_range: "501-1000",
    },
    {
      id: 11,
      name: "CVS Caremark",
      contact: {
        name: "Gail Raynor",
        phone: "1-297-859-6634",
        email: "Ezekiel_Windler30@gmail.com",
        title: "agricultural sciences teacher",
      },
      website: "www.cvsundefinedcaremark.com",
      phone: "823-375-5809 x7248",
      stage: "Not Interested",
      fax: "981-669-1950",
      country: "Estonia",
      territory: "EMEA",
      industry: "Recreational",
      licopage: "www.linkedin.com/company/cvsundefinedcaremark/about",
      employee_range: "10,001+",
    },
    {
      id: 12,
      name: "Fannie Mae",
      contact: {
        name: "Victor Streich",
        phone: "(803) 685-7807 x23769",
        email: "Frederic59@yahoo.com",
        title: "radio operator",
      },
      website: "www.fannieundefinedmae.com",
      phone: "887-500-4487 x91796",
      stage: "Lead",
      fax: "(892) 941-4642 x751",
      country: "Lithuania",
      territory: "EMEA",
      industry: "Alternative Dispute Resolution",
      licopage: "www.linkedin.com/company/fannieundefinedmae/about",
      employee_range: "501-1000",
    },
    {
      id: 13,
      name: "UnitedHealth Group",
      contact: {
        name: "Terrance Lesch",
        phone: "703-257-8583 x00446",
        email: "Allie_Murphy63@gmail.com",
        title: "chemical plant operator",
      },
      website: "www.unitedhealthundefinedgroup.com",
      phone: "1-272-954-2019 x846",
      stage: "Sold",
      fax: "1-944-403-8543 x70973",
      country: "Bouvet Island",
      territory: "EMEA",
      industry: "Education Management",
      licopage: "www.linkedin.com/company/unitedhealthundefinedgroup/about",
      employee_range: "Self-employed",
    },
    {
      id: 14,
      name: "McKesson",
      contact: {
        name: "Greta Waters",
        phone: "(637) 937-7446",
        email: "Duncan_Stoltenberg52@gmail.com",
        title: "geological technician",
      },
      website: "www.mckesson.com",
      phone: "1-488-303-6781",
      stage: "Sold",
      fax: "201-222-5802",
      country: "United States",
      territory: "NAMER",
      industry: "Capital Markets",
      licopage: "www.linkedin.com/company/mckesson/about",
      employee_range: "201-500",
    },
    {
      id: 15,
      name: "Verizon Communications",
      contact: {
        name: "Jaida Breitenberg",
        phone: "933.551.2391 x3970",
        email: "Bulah.Cruickshank@yahoo.com",
        title: "loan officer",
      },
      website: "www.verizonundefinedcommunications.com",
      phone: "(612) 239-8942 x03574",
      stage: "Not Interested",
      fax: "1-390-461-4450 x8266",
      country: "Jordan",
      territory: "EMEA",
      industry: "Machinery",
      licopage: "www.linkedin.com/company/verizonundefinedcommunications/about",
      employee_range: "201-500",
    },
    {
      id: 16,
      name: "Hewlett-Packard",
      contact: {
        name: "Trystan Streich",
        phone: "791.466.5642",
        email: "Mason_Toy24@gmail.com",
        title: "stucco mason",
      },
      website: "www.hewlett-packard.com",
      phone: "469-699-9257 x7037",
      stage: "Sold",
      fax: "(743) 221-8737",
      country: "Guatemala",
      territory: "NAMER",
      industry: "Telecommunications",
      licopage: "www.linkedin.com/company/hewlett-packard/about",
      employee_range: "1001-5000",
    },
    {
      id: 17,
      name: "J.P. Morgan Chase & Co.",
      contact: {
        name: "Jewel Shields",
        phone: "1-806-563-1751 x114",
        email: "Dock_Crist@gmail.com",
        title: "lawyer",
      },
      website: "www.j.p.undefinedmorgan chase & co..com",
      phone: "1-358-659-3617 x942",
      stage: "Lead",
      fax: "(918) 883-8922",
      country: "Congo (Democratic Republic of the)",
      territory: "EMEA",
      industry: "Online Publishing",
      licopage:
        "www.linkedin.com/company/j.p.undefinedmorgan chase & co./about",
      employee_range: "1001-5000",
    },
    {
      id: 18,
      name: "Costco Wholesale",
      contact: {
        name: "Rolando Ratke",
        phone: "837.886.2180",
        email: "Dayna33@gmail.com",
        title: "adult education teacher",
      },
      website: "www.costcoundefinedwholesale.com",
      phone: "800.318.3391 x69036",
      stage: "Sold",
      fax: "416-806-4789",
      country: "Peru",
      territory: "NAMER",
      industry: "Building Materials",
      licopage: "www.linkedin.com/company/costcoundefinedwholesale/about",
      employee_range: "11-50",
    },
    {
      id: 19,
      name: "Express Scripts Holding",
      contact: {
        name: "Marco Ankunding",
        phone: "361.264.0224 x5418",
        email: "Mara_Swaniawski48@yahoo.com",
        title: "food technologist",
      },
      website: "www.expressundefinedscripts holding.com",
      phone: "(497) 993-3221 x41821",
      stage: "Not Interested",
      fax: "1-836-565-9683 x452",
      country: "Togo",
      territory: "EMEA",
      industry: "Translation & Localization",
      licopage:
        "www.linkedin.com/company/expressundefinedscripts holding/about",
      employee_range: "5001-10,000",
    },
    {
      id: 20,
      name: "Bank of America",
      contact: {
        name: "Sidney Mante",
        phone: "1-546-780-7209",
        email: "Tito_Upton17@yahoo.com",
        title: "logging equipment operator",
      },
      website: "www.bankundefinedof america.com",
      phone: "1-500-819-5851 x41520",
      stage: "Lead",
      fax: "988-637-9499 x19180",
      country: "Estonia",
      territory: "EMEA",
      industry: "Broadcast Media",
      licopage: "www.linkedin.com/company/bankundefinedof america/about",
      employee_range: "501-1000",
    },
    {
      id: 21,
      name: "Cardinal Health",
      contact: {
        name: "Jarred Ondricka",
        phone: "864.768.5314 x767",
        email: "Annamarie47@hotmail.com",
        title: "cardiovascular technician",
      },
      website: "www.cardinalundefinedhealth.com",
      phone: "897-833-4875 x64383",
      stage: "Not Interested",
      fax: "316.950.2789 x4936",
      country: "Tanzania",
      territory: "EMEA",
      industry: "Religious Institutions",
      licopage: "www.linkedin.com/company/cardinalundefinedhealth/about",
      employee_range: "11-50",
    },
    {
      id: 22,
      name: "International Business Machines",
      contact: {
        name: "Janick Lockman",
        phone: "900-990-1612",
        email: "Garth13@yahoo.com",
        title: "engine assembler",
      },
      website: "www.internationalundefinedbusiness machines.com",
      phone: "880.413.5594 x2570",
      stage: "Not Interested",
      fax: "499.484.6705 x6277",
      country: "Slovakia",
      territory: "EMEA",
      industry: "Public Safety",
      licopage:
        "www.linkedin.com/company/internationalundefinedbusiness machines/about",
      employee_range: "11-50",
    },
    {
      id: 23,
      name: "Kroger",
      contact: {
        name: "Kaylah Gerlach",
        phone: "569.258.7435",
        email: "Kaelyn86@gmail.com",
        title: "concrete finisher",
      },
      website: "www.kroger.com",
      phone: "1-772-360-5438",
      stage: "Sold",
      fax: "941.235.3137 x12051",
      country: "Uganda",
      territory: "EMEA",
      industry: "Religious Institutions",
      licopage: "www.linkedin.com/company/kroger/about",
      employee_range: "Self-employed",
    },
    {
      id: 24,
      name: "Marathon Petroleum",
      contact: {
        name: "Mariam Hilll",
        phone: "869.721.3939 x80780",
        email: "Aubrey_Stark@hotmail.com",
        title: "industrial machinery mechanic",
      },
      website: "www.marathonundefinedpetroleum.com",
      phone: "528-734-3897 x891",
      stage: "Sold",
      fax: "(566) 417-2280 x30684",
      country: "Ghana",
      territory: "EMEA",
      industry: "Apparel & Fashion",
      licopage: "www.linkedin.com/company/marathonundefinedpetroleum/about",
      employee_range: "11-50",
    },
    {
      id: 25,
      name: "Citigroup",
      contact: {
        name: "Barrett Harvey",
        phone: "1-733-250-9090",
        email: "Juana_Keebler2@hotmail.com",
        title: "mail superintendent",
      },
      website: "www.citigroup.com",
      phone: "(943) 980-3810 x57271",
      stage: "Sold",
      fax: "1-481-830-2687 x67681",
      country: "Cabo Verde",
      territory: "EMEA",
      industry: "Wine & Spirits",
      licopage: "www.linkedin.com/company/citigroup/about",
      employee_range: "10,001+",
    },
    {
      id: 26,
      name: "Archer Daniels Midland",
      contact: {
        name: "Augusta Considine",
        phone: "(625) 275-6851 x16832",
        email: "Vella.Mosciski@hotmail.com",
        title: "fine artist",
      },
      website: "www.archerundefineddaniels midland.com",
      phone: "(505) 262-7047 x3684",
      stage: "Lead",
      fax: "646.594.6290 x313",
      country: "Korea (Republic of)",
      territory: "EMEA",
      industry: "Glass, Ceramics & Concrete",
      licopage: "www.linkedin.com/company/archerundefineddaniels midland/about",
      employee_range: "Self-employed",
    },
    {
      id: 27,
      name: "AmerisourceBergen",
      contact: {
        name: "Alvis Dickens",
        phone: "1-759-380-1276 x4060",
        email: "Annabelle_Huel@hotmail.com",
        title: "marriage therapist",
      },
      website: "www.amerisourcebergen.com",
      phone: "1-311-846-2676 x98173",
      stage: "Not Interested",
      fax: "983.621.0661 x492",
      country: "Swaziland",
      territory: "EMEA",
      industry: "Information Services",
      licopage: "www.linkedin.com/company/amerisourcebergen/about",
      employee_range: "5001-10,000",
    },
    {
      id: 28,
      name: "Wells Fargo",
      contact: {
        name: "Lavonne Rogahn",
        phone: "346.776.1132 x88290",
        email: "Marie37@yahoo.com",
        title: "structural metal fitter",
      },
      website: "www.wellsundefinedfargo.com",
      phone: "456-626-2645 x921",
      stage: "Not Interested",
      fax: "(681) 593-9386 x52244",
      country: "Palestine",
      territory: "EMEA",
      industry: "Information Services",
      licopage: "www.linkedin.com/company/wellsundefinedfargo/about",
      employee_range: "Self-employed",
    },
    {
      id: 29,
      name: "Boeing",
      contact: {
        name: "Lue Lesch",
        phone: "739.383.1639 x935",
        email: "Sylvester_Crist@gmail.com",
        title: "purchasing agent",
      },
      website: "www.boeing.com",
      phone: "976.904.0024 x866",
      stage: "Sold",
      fax: "681-272-6762",
      country: "Ecuador",
      territory: "NAMER",
      industry: "Higher Education",
      licopage: "www.linkedin.com/company/boeing/about",
      employee_range: "1001-5000",
    },
    {
      id: 30,
      name: "Procter & Gamble",
      contact: {
        name: "Sydnie Tremblay",
        phone: "676.742.8629 x9083",
        email: "Melisa_Turner77@hotmail.com",
        title: "assembler",
      },
      website: "www.procterundefined& gamble.com",
      phone: "(380) 748-9724",
      stage: "Sold",
      fax: "1-640-363-0995",
      country: "Anguilla",
      territory: "NAMER",
      industry: "Health, Wellness & Fitness",
      licopage: "www.linkedin.com/company/procterundefined& gamble/about",
      employee_range: "5001-10,000",
    },
    {
      id: 31,
      name: "Freddie Mac",
      contact: {
        name: "Adolphus Hintz",
        phone: "1-348-267-9079 x7346",
        email: "Grayson.Von@gmail.com",
        title: "historian",
      },
      website: "www.freddieundefinedmac.com",
      phone: "453-328-7500 x2331",
      stage: "Not Interested",
      fax: "(666) 505-6033 x650",
      country: "Lithuania",
      territory: "EMEA",
      industry: "Music",
      licopage: "www.linkedin.com/company/freddieundefinedmac/about",
      employee_range: "1001-5000",
    },
    {
      id: 32,
      name: "Home Depot",
      contact: {
        name: "Lucie Thompson",
        phone: "1-331-724-7234 x070",
        email: "Katlyn.Luettgen61@gmail.com",
        title: "precious stone worker",
      },
      website: "www.homeundefineddepot.com",
      phone: "814-319-6720 x130",
      stage: "Not Interested",
      fax: "1-725-628-7246 x44338",
      country: "Poland",
      territory: "EMEA",
      industry: "Law Enforcement",
      licopage: "www.linkedin.com/company/homeundefineddepot/about",
      employee_range: "501-1000",
    },
    {
      id: 33,
      name: "Microsoft",
      contact: {
        name: "Colt Wyman",
        phone: "1-527-607-0541",
        email: "Jamaal_Hagenes@gmail.com",
        title: "gaming investigator",
      },
      website: "www.microsoft.com",
      phone: "527-242-8560",
      stage: "Lead",
      fax: "372-896-1424 x6806",
      country: "Korea (Democratic People’s Republic of)",
      territory: "EMEA",
      industry: "Nonprofit Organization Management",
      licopage: "www.linkedin.com/company/microsoft/about",
      employee_range: "11-50",
    },
    {
      id: 34,
      name: "Amazon.com",
      contact: {
        name: "Kylee Flatley",
        phone: "(729) 562-3812",
        email: "Bettye.Legros@hotmail.com",
        title: "nursing teacher",
      },
      website: "www.amazon.com.com",
      phone: "896.377.9091 x45691",
      stage: "Sold",
      fax: "245.353.0611",
      country: "Åland Islands",
      territory: "EMEA",
      industry: "Mining & Metals",
      licopage: "www.linkedin.com/company/amazon.com/about",
      employee_range: "501-1000",
    },
    {
      id: 35,
      name: "Target",
      contact: {
        name: "Savanna Adams",
        phone: "(948) 404-5506 x40406",
        email: "Carlee.Greenholt16@yahoo.com",
        title: "faller",
      },
      website: "www.target.com",
      phone: "(483) 398-3784 x482",
      stage: "Sold",
      fax: "1-626-932-5384 x2532",
      country: "Poland",
      territory: "EMEA",
      industry: "Online Publishing",
      licopage: "www.linkedin.com/company/target/about",
      employee_range: "1001-5000",
    },
    {
      id: 36,
      name: "Walgreen Co.",
      contact: {
        name: "Columbus Blanda",
        phone: "1-915-716-7012",
        email: "Maud.Haley76@yahoo.com",
        title: "information security analyst",
      },
      website: "www.walgreenundefinedco..com",
      phone: "958.435.7138",
      stage: "Not Interested",
      fax: "484.594.8190 x73521",
      country: "Slovenia",
      territory: "EMEA",
      industry: "Luxury Goods & Jewelry",
      licopage: "www.linkedin.com/company/walgreenundefinedco./about",
      employee_range: "11-50",
    },
    {
      id: 37,
      name: "WellPoint",
      contact: {
        name: "Eldora Crist",
        phone: "475-663-0002 x0881",
        email: "Dora.Olson@gmail.com",
        title: "semiconductor processor",
      },
      website: "www.wellpoint.com",
      phone: "218-542-9235",
      stage: "Sold",
      fax: "1-373-317-6611 x88094",
      country: "Jersey",
      territory: "EMEA",
      industry: "Renewables & Environment",
      licopage: "www.linkedin.com/company/wellpoint/about",
      employee_range: "10,001+",
    },
    {
      id: 38,
      name: "Johnson & Johnson",
      contact: {
        name: "Maria Cummings",
        phone: "(618) 313-6825 x71935",
        email: "Gretchen37@gmail.com",
        title: "financial manager",
      },
      website: "www.johnsonundefined& johnson.com",
      phone: "(833) 996-4628 x954",
      stage: "Lead",
      fax: "(581) 228-5610",
      country: "Tunisia",
      territory: "EMEA",
      industry: "Writing & Editing",
      licopage: "www.linkedin.com/company/johnsonundefined& johnson/about",
      employee_range: "201-500",
    },
    {
      id: 39,
      name: "American International Group",
      contact: {
        name: "Khalil Price",
        phone: "(958) 537-8033 x6674",
        email: "Nick.Champlin@hotmail.com",
        title: "soil scientist",
      },
      website: "www.americanundefinedinternational group.com",
      phone: "(879) 238-2046",
      stage: "Not Interested",
      fax: "239.380.1297",
      country: "Cameroon",
      territory: "EMEA",
      industry: "Religious Institutions",
      licopage:
        "www.linkedin.com/company/americanundefinedinternational group/about",
      employee_range: "Self-employed",
    },
    {
      id: 40,
      name: "State Farm Insurance Cos.",
      contact: {
        name: "Bethel Casper",
        phone: "(435) 898-6984 x19882",
        email: "Zena.Torphy98@hotmail.com",
        title: "rail-track laying equipment operator",
      },
      website: "www.stateundefinedfarm insurance cos..com",
      phone: "276.354.1369 x00945",
      stage: "Sold",
      fax: "1-953-970-4609",
      country: "Cayman Islands",
      territory: "NAMER",
      industry: "Shipbuilding",
      licopage:
        "www.linkedin.com/company/stateundefinedfarm insurance cos./about",
      employee_range: "1-10",
    },
    {
      id: 41,
      name: "MetLife",
      contact: {
        name: "Alva Legros",
        phone: "778-801-5554",
        email: "Norwood_Boyer@hotmail.com",
        title: "door-to-door sales worker",
      },
      website: "www.metlife.com",
      phone: "246-955-9495 x4353",
      stage: "Sold",
      fax: "243.783.6322 x38963",
      country: "Gibraltar",
      territory: "EMEA",
      industry: "Biotechnology",
      licopage: "www.linkedin.com/company/metlife/about",
      employee_range: "51-200",
    },
    {
      id: 42,
      name: "PepsiCo",
      contact: {
        name: "Curt Stokes",
        phone: "1-672-293-6255 x6580",
        email: "Abner_Bradtke@gmail.com",
        title: "childcare worker",
      },
      website: "www.pepsico.com",
      phone: "(395) 268-5361",
      stage: "Sold",
      fax: "1-922-912-6166 x90983",
      country: "Burkina Faso",
      territory: "EMEA",
      industry: "Leisure & Travel",
      licopage: "www.linkedin.com/company/pepsico/about",
      employee_range: "11-50",
    },
    {
      id: 43,
      name: "Comcast",
      contact: {
        name: "Robbie Reichel",
        phone: "325.785.9077",
        email: "Roma.Veum@yahoo.com",
        title: "compensation and benefits manager",
      },
      website: "www.comcast.com",
      phone: "560.502.4050 x17622",
      stage: "Sold",
      fax: "255-271-5165 x088",
      country: "Haiti",
      territory: "NAMER",
      industry: "Human Resources",
      licopage: "www.linkedin.com/company/comcast/about",
      employee_range: "5001-10,000",
    },
    {
      id: 44,
      name: "United Technologies",
      contact: {
        name: "Yesenia Hansen",
        phone: "(652) 362-0568",
        email: "Magnus.Upton@gmail.com",
        title: "auto damage insurance appraiser",
      },
      website: "www.unitedundefinedtechnologies.com",
      phone: "(601) 277-2052 x8034",
      stage: "Lead",
      fax: "(434) 997-5368",
      country: "Falkland Islands",
      territory: "EMEA",
      industry: "Museums & Institutions",
      licopage: "www.linkedin.com/company/unitedundefinedtechnologies/about",
      employee_range: "1-10",
    },
    {
      id: 45,
      name: "Google",
      contact: {
        name: "Horace Borer",
        phone: "1-692-549-6313",
        email: "Cleta72@yahoo.com",
        title: "timing device assembler",
      },
      website: "www.google.com",
      phone: "533-607-8785 x79817",
      stage: "Lead",
      fax: "1-323-226-4707 x99875",
      country: "Ukraine",
      territory: "EMEA",
      industry: "Computer Networking",
      licopage: "www.linkedin.com/company/google/about",
      employee_range: "1-10",
    },
    {
      id: 46,
      name: "ConocoPhillips",
      contact: {
        name: "Luther Rath",
        phone: "(231) 752-2193",
        email: "Austen.Rath@hotmail.com",
        title: "electrical power-line installer",
      },
      website: "www.conocophillips.com",
      phone: "360-671-4466 x86608",
      stage: "Lead",
      fax: "380.896.6355 x36660",
      country: "Slovakia",
      territory: "EMEA",
      industry: "Public Safety",
      licopage: "www.linkedin.com/company/conocophillips/about",
      employee_range: "10,001+",
    },
    {
      id: 47,
      name: "Dow Chemical",
      contact: {
        name: "Gilberto Lubowitz",
        phone: "(522) 441-9675 x128",
        email: "Chaim62@yahoo.com",
        title: "insulation worker",
      },
      website: "www.dowundefinedchemical.com",
      phone: "(603) 522-2695 x24069",
      stage: "Sold",
      fax: "1-792-911-7163 x6227",
      country: "Israel",
      territory: "EMEA",
      industry: "Libraries",
      licopage: "www.linkedin.com/company/dowundefinedchemical/about",
      employee_range: "11-50",
    },
    {
      id: 48,
      name: "Caterpillar",
      contact: {
        name: "Caroline Hudson",
        phone: "872-749-6881 x329",
        email: "Angelica.Champlin37@hotmail.com",
        title: "tire builder",
      },
      website: "www.caterpillar.com",
      phone: "1-290-260-2360 x170",
      stage: "Sold",
      fax: "557.954.2547",
      country: "Slovakia",
      territory: "EMEA",
      industry: "Information Technology & Services",
      licopage: "www.linkedin.com/company/caterpillar/about",
      employee_range: "5001-10,000",
    },
    {
      id: 49,
      name: "Box",
      contact: {
        name: "Gennaro Murray",
        phone: "667.709.1439",
        email: "Felicia_Kassulke@gmail.com",
        title: "english language teacher",
      },
      website: "www.box.com",
      phone: "(518) 939-0900",
      stage: "Lead",
      fax: "604-724-7078 x7918",
      country: "Anguilla",
      territory: "NAMER",
      industry: "International Trade & Development",
      licopage: "www.linkedin.com/company/box/about",
      employee_range: "501-1000",
    },
  ],
};
