export default {
  accountList: [
    {
      id: "f-m7-hyFzkf0HSEeQ2s-9A",
      stage: "lead",
      alias: "fog-harbor-fish-house-san-francisco-2",
      name: "Fog Harbor Fish House",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/M6WJatZbR7VahSi6HSgONg/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/fog-harbor-fish-house-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 6210,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.809041,
        longitude: -122.410233,
      },
      transactions: ["restaurant_reservation"],
      price: "$$",
      location: {
        address1: "The Embarcadero",
        address2: "Ste A-202",
        address3: "",
        city: "San Francisco",
        zip_code: "94133",
        country: "US",
        state: "CA",
        display_address: [
          "The Embarcadero",
          "Ste A-202",
          "San Francisco, CA 94133",
        ],
      },
      phone: "+14154212442",
      display_phone: "(415) 421-2442",
      distance: 5827.740044156521,
    },
    {
      id: "eYXwVR4mMAjzkJnm5wneHQ",
      stage: "lead",
      alias: "burma-superstar-san-francisco-2",
      name: "Burma Superstar",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/Rt-zOS-uNY0cafsq1UeoDw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/burma-superstar-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 6812,
      categories: [
        {
          alias: "burmese",
          title: "Burmese",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.782787322998,
        longitude: -122.462539672852,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "309 Clement St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94118",
        country: "US",
        state: "CA",
        display_address: ["309 Clement St", "San Francisco, CA 94118"],
      },
      phone: "+14153872147",
      display_phone: "(415) 387-2147",
      distance: 3348.056372269087,
    },
    {
      id: "LsGkxQK217twdzZzVXsSRg",
      stage: "closed",
      alias: "creola-san-francisco-3",
      name: "CreoLa",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/hI7JpT0HZZyciCfGlkjW6w/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/creola-san-francisco-3?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 37,
      categories: [
        {
          alias: "bars",
          title: "Bars",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "cajun",
          title: "Cajun/Creole",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.7662642,
        longitude: -122.4527631,
      },
      transactions: ["restaurant_reservation", "delivery"],
      location: {
        address1: "900 Stanyan St",
        address2: "",
        address3: null,
        city: "San Francisco",
        zip_code: "94117",
        country: "US",
        state: "CA",
        display_address: ["900 Stanyan St", "San Francisco, CA 94117"],
      },
      phone: "+14152603143",
      display_phone: "(415) 260-3143",
      distance: 1550.8836410478934,
    },
    {
      id: "8kck3-K4zYKTJbJko0JlXQ",
      stage: "",
      alias: "farmhouse-kitchen-thai-cuisine-san-francisco",
      name: "Farmhouse Kitchen Thai Cuisine",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/M7XNGbZBSbz8_WZ9XCslzA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/farmhouse-kitchen-thai-cuisine-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2576,
      categories: [
        {
          alias: "thai",
          title: "Thai",
        },
        {
          alias: "comfortfood",
          title: "Comfort Food",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.76026094,
        longitude: -122.4112048,
      },
      transactions: ["restaurant_reservation", "pickup", "delivery"],
      price: "$$",
      location: {
        address1: "710 Florida St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94110",
        country: "US",
        state: "CA",
        display_address: ["710 Florida St", "San Francisco, CA 94110"],
      },
      phone: "+14158142920",
      display_phone: "(415) 814-2920",
      distance: 2220.139249062676,
    },
    {
      id: "OOlS_RmdMk1LHtgOQWoHoA",
      stage: "",
      alias: "tanglad-san-francisco",
      name: "Tanglad",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/3IfqA1yAQiORvxd8ccNmyA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/tanglad-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 12,
      categories: [
        {
          alias: "vietnamese",
          title: "Vietnamese",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.761492,
        longitude: -122.434844,
      },
      transactions: ["pickup", "delivery"],
      location: {
        address1: "469 Castro St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94114",
        country: "US",
        state: "CA",
        display_address: ["469 Castro St", "San Francisco, CA 94114"],
      },
      phone: "+14156243238",
      display_phone: "(415) 624-3238",
      distance: 159.10650212292109,
    },
    {
      id: "M0JTO3oyu6gxh1mfFjU-dA",
      stage: "closed",
      alias: "san-tung-san-francisco-2",
      name: "San Tung",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/pvWRWivkeyGy7g7UF9Me1g/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/san-tung-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 6965,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
        {
          alias: "chicken_wings",
          title: "Chicken Wings",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.763693,
        longitude: -122.469008,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "1031 Irving St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94122",
        country: "US",
        state: "CA",
        display_address: ["1031 Irving St", "San Francisco, CA 94122"],
      },
      phone: "+14152420828",
      display_phone: "(415) 242-0828",
      distance: 2877.9920007894843,
    },
    {
      id: "dY0Mc_PHH6nLENvWmVtwxQ",
      stage: "",
      alias: "daeho-kalbijjim-and-beef-soup-san-francisco-9",
      name: "Daeho Kalbijjim & Beef Soup",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/LaFYy38ZDs39NsqIm6Wz4g/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/daeho-kalbijjim-and-beef-soup-san-francisco-9?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 843,
      categories: [
        {
          alias: "korean",
          title: "Korean",
        },
        {
          alias: "soup",
          title: "Soup",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.78601,
        longitude: -122.42858,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1620 Post St",
        address2: "",
        address3: null,
        city: "San Francisco",
        zip_code: "94115",
        country: "US",
        state: "CA",
        display_address: ["1620 Post St", "San Francisco, CA 94115"],
      },
      phone: "+14155631388",
      display_phone: "(415) 563-1388",
      distance: 2867.8335670207744,
    },
    {
      id: "DpIphLvQx6FVaTbLdqcdEg",
      stage: "lead",
      alias: "hoshinoya-san-francisco",
      name: "Hoshinoya",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/BLFgHAjmLVlFgUuoT7AmTA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/hoshinoya-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 22,
      categories: [
        {
          alias: "japanese",
          title: "Japanese",
        },
        {
          alias: "thai",
          title: "Thai",
        },
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.78621,
        longitude: -122.429756,
      },
      transactions: ["delivery"],
      location: {
        address1: "1740 Buchanan St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94115",
        country: "US",
        state: "CA",
        display_address: ["1740 Buchanan St", "San Francisco, CA 94115"],
      },
      phone: "+14156103929",
      display_phone: "(415) 610-3929",
      distance: 2873.3284031636304,
    },
    {
      id: "wxzx3duu1c0CcomzEOvfOQ",
      stage: "closed",
      alias: "the-front-porch-san-francisco",
      name: "The Front Porch",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/0fmMVyqSKOMIqtkQksUTUQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/the-front-porch-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2857,
      categories: [
        {
          alias: "southern",
          title: "Southern",
        },
        {
          alias: "cajun",
          title: "Cajun/Creole",
        },
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7438,
        longitude: -122.422035,
      },
      transactions: ["restaurant_reservation", "pickup", "delivery"],
      price: "$$",
      location: {
        address1: "65 29th St",
        address2: "Ste A",
        address3: "",
        city: "San Francisco",
        zip_code: "94110",
        country: "US",
        state: "CA",
        display_address: ["65 29th St", "Ste A", "San Francisco, CA 94110"],
      },
      phone: "+14156957800",
      display_phone: "(415) 695-7800",
      distance: 2285.237602234066,
    },
    {
      id: "kvrQecqdGvnuVICMstZJmA",
      stage: "lead",
      alias: "dumpling-home-san-francisco",
      name: "Dumpling Home",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/3QoBn9D3s1Qkom-TOm5snw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/dumpling-home-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 25,
      categories: [
        {
          alias: "dimsum",
          title: "Dim Sum",
        },
        {
          alias: "noodles",
          title: "Noodles",
        },
        {
          alias: "asianfusion",
          title: "Asian Fusion",
        },
      ],
      rating: 5.0,
      coordinates: {
        latitude: 37.77571,
        longitude: -122.42257,
      },
      transactions: [],
      location: {
        address1: "298 Gough St",
        address2: "",
        address3: null,
        city: "San Francisco",
        zip_code: "94102",
        country: "US",
        state: "CA",
        display_address: ["298 Gough St", "San Francisco, CA 94102"],
      },
      phone: "+14155031666",
      display_phone: "(415) 503-1666",
      distance: 2055.8477804471563,
    },
    {
      id: "XhJ6ZYagcWNHpJ1H1KvNlQ",
      stage: "closed",
      alias: "a-mano-san-francisco-2",
      name: "a Mano",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/ezG_zJwov2QNZwyK14EkwA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/a-mano-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 931,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.776963880538,
        longitude: -122.423868469312,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "450 Hayes St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94102",
        country: "US",
        state: "CA",
        display_address: ["450 Hayes St", "San Francisco, CA 94102"],
      },
      phone: "+14155067401",
      display_phone: "(415) 506-7401",
      distance: 2100.777699621916,
    },
    {
      id: "g2ktKLz4rNTi8T5WUEUYuw",
      stage: "lead",
      alias: "the-monks-kettle-san-francisco",
      name: "The Monk's Kettle",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/dH6xyaBjuIEIzPMAw4_27g/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/the-monks-kettle-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2202,
      categories: [
        {
          alias: "bars",
          title: "Bars",
        },
        {
          alias: "gastropubs",
          title: "Gastropubs",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7647290879634,
        longitude: -122.42297490884,
      },
      transactions: ["restaurant_reservation", "pickup", "delivery"],
      price: "$$",
      location: {
        address1: "3141 16th St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94103",
        country: "US",
        state: "CA",
        display_address: ["3141 16th St", "San Francisco, CA 94103"],
      },
      phone: "+14158659523",
      display_phone: "(415) 865-9523",
      distance: 1258.5167351110315,
    },
    {
      id: "WavvLdfdP6g8aZTtbBQHTw",
      stage: "",
      alias: "gary-danko-san-francisco",
      name: "Gary Danko",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/CAprIoeKQAYV9oUw9xBbmA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/gary-danko-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 5522,
      categories: [
        {
          alias: "newamerican",
          title: "American (New)",
        },
        {
          alias: "french",
          title: "French",
        },
        {
          alias: "wine_bars",
          title: "Wine Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.80587,
        longitude: -122.42058,
      },
      transactions: [],
      price: "$$$$",
      location: {
        address1: "800 N Point St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94109",
        country: "US",
        state: "CA",
        display_address: ["800 N Point St", "San Francisco, CA 94109"],
      },
      phone: "+14157492060",
      display_phone: "(415) 749-2060",
      distance: 5191.341803207417,
    },
    {
      id: "Xg-FyjVKAN70LO4u4Z1ozg",
      stage: "closed",
      alias: "hog-island-oyster-co-san-francisco",
      name: "Hog Island Oyster Co",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/TW9FgV_Ufqd15t_ARQuz1A/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/hog-island-oyster-co-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 6039,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "seafoodmarkets",
          title: "Seafood Markets",
        },
        {
          alias: "raw_food",
          title: "Live/Raw Food",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.795831,
        longitude: -122.393303,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "1 Ferry Bldg",
        address2: "",
        address3: "Shop 11",
        city: "San Francisco",
        zip_code: "94111",
        country: "US",
        state: "CA",
        display_address: ["1 Ferry Bldg", "Shop 11", "San Francisco, CA 94111"],
      },
      phone: "+14153917117",
      display_phone: "(415) 391-7117",
      distance: 5428.15670676801,
    },
    {
      id: "-qRM2Xazaq2S0WkhLp99YA",
      stage: "lead",
      alias: "lost-resort-san-francisco",
      name: "Lost Resort",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/Kzs_PmxZdNvZ5sQqf-d-jw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/lost-resort-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 22,
      categories: [
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.75948,
        longitude: -122.40873,
      },
      transactions: [],
      location: {
        address1: "2736 20th St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94110",
        country: "US",
        state: "CA",
        display_address: ["2736 20th St", "San Francisco, CA 94110"],
      },
      phone: "+14152370770",
      display_phone: "(415) 237-0770",
      distance: 2440.109010645074,
    },
    {
      id: "PsY5DMHxa5iNX_nX0T-qPA",
      stage: "closed",
      alias: "kokkari-estiatorio-san-francisco",
      name: "Kokkari Estiatorio",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/7StMTfE2srlcIu2opeTb3g/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/kokkari-estiatorio-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 4533,
      categories: [
        {
          alias: "greek",
          title: "Greek",
        },
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.796996,
        longitude: -122.399661,
      },
      transactions: ["delivery"],
      price: "$$$",
      location: {
        address1: "200 Jackson St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94111",
        country: "US",
        state: "CA",
        display_address: ["200 Jackson St", "San Francisco, CA 94111"],
      },
      phone: "+14159810983",
      display_phone: "(415) 981-0983",
      distance: 5153.879756630951,
    },
    {
      id: "kOYj2sGMZnyC1lU-_Uw5fA",
      stage: "lead",
      alias: "cha-cha-cha-san-francisco-4",
      name: "Cha Cha Cha",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/rTRFT63eDRgi59LPQyYXcg/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/cha-cha-cha-san-francisco-4?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 3220,
      categories: [
        {
          alias: "caribbean",
          title: "Caribbean",
        },
        {
          alias: "cuban",
          title: "Cuban",
        },
        {
          alias: "tapas",
          title: "Tapas Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7691434,
        longitude: -122.4520399,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "1801 Haight St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94117",
        country: "US",
        state: "CA",
        display_address: ["1801 Haight St", "San Francisco, CA 94117"],
      },
      phone: "+14153867670",
      display_phone: "(415) 386-7670",
      distance: 1648.936701704209,
    },
    {
      id: "PDhfVvcVXgBinZf5I6s1KQ",
      stage: "",
      alias: "the-codmother-fish-and-chips-san-francisco-3",
      name: "The Codmother Fish & Chips",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/jIiYLWAA1S-efjnkLJ29FQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/the-codmother-fish-and-chips-san-francisco-3?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2988,
      categories: [
        {
          alias: "british",
          title: "British",
        },
        {
          alias: "fishnchips",
          title: "Fish & Chips",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.8072702557489,
        longitude: -122.417093771758,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "496 Beach St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94133",
        country: "US",
        state: "CA",
        display_address: ["496 Beach St", "San Francisco, CA 94133"],
      },
      phone: "+14156069349",
      display_phone: "(415) 606-9349",
      distance: 5429.459284841022,
    },
    {
      id: "cbkbw0-QUwRZWV49JpDCWA",
      stage: "lead",
      alias: "wildseed-san-francisco-2",
      name: "Wildseed",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/u08PO92_L37rJy1bVvCrpA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/wildseed-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 370,
      categories: [
        {
          alias: "vegetarian",
          title: "Vegetarian",
        },
        {
          alias: "vegan",
          title: "Vegan",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.7976259,
        longitude: -122.432446,
      },
      transactions: ["restaurant_reservation", "delivery"],
      price: "$$",
      location: {
        address1: "2000 Union St",
        address2: null,
        address3: null,
        city: "San Francisco",
        zip_code: "94123",
        country: "US",
        state: "CA",
        display_address: ["2000 Union St", "San Francisco, CA 94123"],
      },
      phone: "+14158727350",
      display_phone: "(415) 872-7350",
      distance: 4098.90861923779,
    },
    {
      id: "BI40rGhpngLNPacrjWpseQ",
      stage: "",
      alias: "dumpling-kitchen-san-francisco",
      name: "Dumpling Kitchen",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/iqOGihbmUTproT-gMIosFA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/dumpling-kitchen-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 1596,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7423,
        longitude: -122.48701,
      },
      transactions: ["pickup", "delivery"],
      price: "$$",
      location: {
        address1: "1935 Taraval St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94116",
        country: "US",
        state: "CA",
        display_address: ["1935 Taraval St", "San Francisco, CA 94116"],
      },
      phone: "+14156828938",
      display_phone: "(415) 682-8938",
      distance: 4904.15624633216,
    },
    {
      id: "BI40rGhpngLNPacrjWpseQ",
      stage: "closed",
      alias: "dumpling-kitchen-san-francisco",
      name: "Dumpling Kitchen",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/iqOGihbmUTproT-gMIosFA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/dumpling-kitchen-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 1597,
      categories: [
        {
          alias: "chinese",
          title: "Chinese",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7423,
        longitude: -122.48701,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1935 Taraval St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94116",
        country: "US",
        state: "CA",
        display_address: ["1935 Taraval St", "San Francisco, CA 94116"],
      },
      phone: "+14156828938",
      display_phone: "(415) 682-8938",
      distance: 4904.15624633216,
    },
    {
      id: "YbUD7-Z2Be5thHaybd7ssQ",
      stage: "lead",
      alias: "alchemist-bar-and-lounge-san-francisco",
      name: "Alchemist Bar & Lounge",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/p3j7jCSOk4RMdbxpBKiO3Q/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/alchemist-bar-and-lounge-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 429,
      categories: [
        {
          alias: "lounges",
          title: "Lounges",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "newamerican",
          title: "American (New)",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7791800203336,
        longitude: -122.392967912689,
      },
      transactions: ["restaurant_reservation"],
      price: "$$",
      location: {
        address1: "679 3rd St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94107",
        country: "US",
        state: "CA",
        display_address: ["679 3rd St", "San Francisco, CA 94107"],
      },
      phone: "+14157469968",
      display_phone: "(415) 746-9968",
      distance: 4328.646161272035,
    },
    {
      id: "mSMZJj2pFvttWLpcDmgrEA",
      stage: "",
      alias: "tonys-pizza-napoletana-san-francisco",
      name: "Tony's Pizza Napoletana",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/rrBlePEDLrbD27VVE0Ze2A/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/tonys-pizza-napoletana-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 5166,
      categories: [
        {
          alias: "pizza",
          title: "Pizza",
        },
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.8003315377662,
        longitude: -122.409053979377,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "1570 Stockton St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94133",
        country: "US",
        state: "CA",
        display_address: ["1570 Stockton St", "San Francisco, CA 94133"],
      },
      phone: "+14158359888",
      display_phone: "(415) 835-9888",
      distance: 5002.084940639829,
    },
    {
      id: "8dUaybEPHsZMgr1iKgqgMQ",
      stage: "lead",
      alias: "sotto-mare-oysteria-and-seafood-san-francisco",
      name: "Sotto Mare Oysteria & Seafood",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/o3hIcGLMxV_5ynxEjGWGrw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/sotto-mare-oysteria-and-seafood-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 3798,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "bars",
          title: "Bars",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.79979,
        longitude: -122.40834,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "552 Green St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94133",
        country: "US",
        state: "CA",
        display_address: ["552 Green St", "San Francisco, CA 94133"],
      },
      phone: "+14153983181",
      display_phone: "(415) 398-3181",
      distance: 4980.8804673363975,
    },
    {
      id: "voFE8DTKsTFi1Vzm_zzd0Q",
      stage: "lead",
      alias: "don-pistos-san-francisco-2",
      name: "Don Pistos",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/tqKd3ieOr9mCTJ6z6xS-Pg/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/don-pistos-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 1812,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "salad",
          title: "Salad",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.800773,
        longitude: -122.407964,
      },
      transactions: ["restaurant_reservation", "delivery", "pickup"],
      price: "$$",
      location: {
        address1: "510 Union St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94133",
        country: "US",
        state: "CA",
        display_address: ["510 Union St", "San Francisco, CA 94133"],
      },
      phone: "+14153950939",
      display_phone: "(415) 395-0939",
      distance: 5089.089100642661,
    },
    {
      id: "PgJV1wOtwTuoUz_n5Mcyxw",
      stage: "closed",
      alias: "tacos-el-patrón-san-francisco-2",
      name: "Tacos El Patrón",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/fkgyZbyYP7evChd0trFinA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/tacos-el-patr%C3%B3n-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 358,
      categories: [
        {
          alias: "tacos",
          title: "Tacos",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.748949,
        longitude: -122.416138,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "1500 S Van Ness Ave",
        address2: "Ste 100",
        address3: "",
        city: "San Francisco",
        zip_code: "94110",
        country: "US",
        state: "CA",
        display_address: [
          "1500 S Van Ness Ave",
          "Ste 100",
          "San Francisco, CA 94110",
        ],
      },
      phone: "+14158297315",
      display_phone: "(415) 829-7315",
      distance: 2224.9476542375687,
    },
    {
      id: "z9CN58fSrA46ggyb6OnCnQ",
      stage: "lead",
      alias: "thanh-long-san-francisco",
      name: "Thanh Long",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/M2MVCe-Ab8-d3K0W70NZCA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/thanh-long-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2723,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "vietnamese",
          title: "Vietnamese",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.76017,
        longitude: -122.50609,
      },
      transactions: ["restaurant_reservation", "delivery"],
      price: "$$$",
      location: {
        address1: "4101 Judah St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94122",
        country: "US",
        state: "CA",
        display_address: ["4101 Judah St", "San Francisco, CA 94122"],
      },
      phone: "+14156651146",
      display_phone: "(415) 665-1146",
      distance: 6122.811241757456,
    },
    {
      id: "VPXezwmTETrwitrzj9BZPA",
      stage: "lead",
      alias: "dumpling-time-san-francisco",
      name: "Dumpling Time",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/LpVJS1JQ5thyPRCT99mMCQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/dumpling-time-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 1930,
      categories: [
        {
          alias: "dimsum",
          title: "Dim Sum",
        },
        {
          alias: "asianfusion",
          title: "Asian Fusion",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7697533,
        longitude: -122.4022546,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "11 Division St",
        address2: "",
        address3: null,
        city: "San Francisco",
        zip_code: "94103",
        country: "US",
        state: "CA",
        display_address: ["11 Division St", "San Francisco, CA 94103"],
      },
      phone: "+14155254797",
      display_phone: "(415) 525-4797",
      distance: 3151.2428912681967,
    },
    {
      id: "BjlVE7tTp1UCEttgkM1Big",
      stage: "lead",
      alias: "beit-rima-san-francisco-3",
      name: "Beit Rima",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/BfaG5TQ_92HpQuHqiLl9VQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/beit-rima-san-francisco-3?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 351,
      categories: [
        {
          alias: "arabian",
          title: "Arabian",
        },
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
        {
          alias: "lebanese",
          title: "Lebanese",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.76872,
        longitude: -122.42943,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "138 Church St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94114",
        country: "US",
        state: "CA",
        display_address: ["138 Church St", "San Francisco, CA 94114"],
      },
      phone: "+14157030270",
      display_phone: "(415) 703-0270",
      distance: 1073.1993439779797,
    },
    {
      id: "I8T8aoAsFQYwQiRvLBayFA",
      stage: "closed",
      alias:
        "il-casaro-pizzeria-and-mozzarella-bar-north-beach-location-san-francisco",
      name: "Il Casaro Pizzeria & Mozzarella Bar - North Beach Location",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/ef3tF8ogJIycWxOd9cKCsw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/il-casaro-pizzeria-and-mozzarella-bar-north-beach-location-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 1201,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.79852,
        longitude: -122.40739,
      },
      transactions: ["restaurant_reservation", "delivery", "pickup"],
      price: "$$",
      location: {
        address1: "348 Columbus Ave",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94133",
        country: "US",
        state: "CA",
        display_address: ["348 Columbus Ave", "San Francisco, CA 94133"],
      },
      phone: "+14156779455",
      display_phone: "(415) 677-9455",
      distance: 4901.8974228210545,
    },
    {
      id: "QQkroHtwS96-dzMpT4a-DA",
      stage: "lead",
      alias: "delarosa-san-francisco",
      name: "Delarosa",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/ADrarUkNN9kuVbyPae0HyQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/delarosa-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 1553,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.800287,
        longitude: -122.439110224537,
      },
      transactions: ["restaurant_reservation"],
      price: "$$",
      location: {
        address1: "2175 Chestnut St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94123",
        country: "US",
        state: "CA",
        display_address: ["2175 Chestnut St", "San Francisco, CA 94123"],
      },
      phone: "+14156737100",
      display_phone: "(415) 673-7100",
      distance: 4385.946516592388,
    },
    {
      id: "HHtpR0RslupSQ99GIIwW5A",
      stage: "lead",
      alias: "marufuku-ramen-sf-san-francisco",
      name: "Marufuku Ramen SF",
      image_url:
        "https://s3-media4.fl.yelpcdn.com/bphoto/ouK2VmW0SrI70jsJpTxJhw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/marufuku-ramen-sf-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 3052,
      categories: [
        {
          alias: "ramen",
          title: "Ramen",
        },
      ],
      rating: 4.5,
      coordinates: {
        latitude: 37.785014,
        longitude: -122.431842,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1581 Webster St",
        address2: "Ste 235",
        address3: null,
        city: "San Francisco",
        zip_code: "94115",
        country: "US",
        state: "CA",
        display_address: [
          "1581 Webster St",
          "Ste 235",
          "San Francisco, CA 94115",
        ],
      },
      phone: "+14158729786",
      display_phone: "(415) 872-9786",
      distance: 2710.1678399585257,
    },
    {
      id: "HaAb_L9zVNLjJwrBkSf_Vw",
      stage: "lead",
      alias: "pier-market-seafood-restaurant-san-francisco",
      name: "Pier Market Seafood Restaurant",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/49kjzgq8wYJxP3jq4TlK2g/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/pier-market-seafood-restaurant-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2158,
      categories: [
        {
          alias: "seafood",
          title: "Seafood",
        },
        {
          alias: "bars",
          title: "Bars",
        },
        {
          alias: "sandwiches",
          title: "Sandwiches",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.8099386456994,
        longitude: -122.410550415516,
      },
      transactions: ["restaurant_reservation"],
      price: "$$",
      location: {
        address1: "The Embarcadero",
        address2: "Ste 103",
        address3: "",
        city: "San Francisco",
        zip_code: "94133",
        country: "US",
        state: "CA",
        display_address: [
          "The Embarcadero",
          "Ste 103",
          "San Francisco, CA 94133",
        ],
      },
      phone: "+14159897437",
      display_phone: "(415) 989-7437",
      distance: 5908.750879956415,
    },
    {
      id: "9acPdpguULGPbChPwpS3aw",
      stage: "closed",
      alias: "ragazza-san-francisco",
      name: "Ragazza",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/GtHPmSQffPr7zuppDVgh7A/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/ragazza-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 666,
      categories: [
        {
          alias: "italian",
          title: "Italian",
        },
        {
          alias: "pizza",
          title: "Pizza",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.772476,
        longitude: -122.437473,
      },
      transactions: ["restaurant_reservation", "delivery"],
      price: "$$",
      location: {
        address1: "311 Divisadero St",
        address2: "",
        address3: "",
        city: "San Francisco",
        zip_code: "94117",
        country: "US",
        state: "CA",
        display_address: ["311 Divisadero St", "San Francisco, CA 94117"],
      },
      phone: "+14152551133",
      display_phone: "(415) 255-1133",
      distance: 1290.4133984521532,
    },
    {
      id: "aSeldMKv9G6_8-gV0bjwvw",
      stage: "lead",
      alias: "the-cheesecake-factory-san-francisco-2",
      name: "The Cheesecake Factory",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/nIYDxWlgNejmBgLwbHCt5A/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/the-cheesecake-factory-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 3255,
      categories: [
        {
          alias: "desserts",
          title: "Desserts",
        },
        {
          alias: "tradamerican",
          title: "American (Traditional)",
        },
      ],
      rating: 3.0,
      coordinates: {
        latitude: 37.7872658401153,
        longitude: -122.407448,
      },
      transactions: [],
      price: "$$",
      location: {
        address1: "251 Geary St",
        address2: "",
        address3: "Union Square",
        city: "San Francisco",
        zip_code: "94102",
        country: "US",
        state: "CA",
        display_address: [
          "251 Geary St",
          "Union Square",
          "San Francisco, CA 94102",
        ],
      },
      phone: "+14153914444",
      display_phone: "(415) 391-4444",
      distance: 3884.8242921036167,
    },
    {
      id: "tKmqlKWOMMiU8pn0gLliXA",
      stage: "lead",
      alias: "flores-san-francisco",
      name: "Flores",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/zcXf5H14-zautn9q2-XxHw/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/flores-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 530,
      categories: [
        {
          alias: "mexican",
          title: "Mexican",
        },
        {
          alias: "cocktailbars",
          title: "Cocktail Bars",
        },
        {
          alias: "breakfast_brunch",
          title: "Breakfast & Brunch",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7976161048577,
        longitude: -122.432580590249,
      },
      transactions: ["restaurant_reservation", "delivery"],
      price: "$$",
      location: {
        address1: "2030 Union St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94123",
        country: "US",
        state: "CA",
        display_address: ["2030 Union St", "San Francisco, CA 94123"],
      },
      phone: "+14157962926",
      display_phone: "(415) 796-2926",
      distance: 4096.825382245225,
    },
    {
      id: "xv8dq_jBNfQkHeX2wJGlAg",
      stage: "",
      alias: "coqueta-san-francisco",
      name: "Coqueta",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/AzJr_HMdWjsKAWb-b5h1RA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/coqueta-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2100,
      categories: [
        {
          alias: "spanish",
          title: "Spanish",
        },
        {
          alias: "tapasmallplates",
          title: "Tapas/Small Plates",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.798588,
        longitude: -122.396639,
      },
      transactions: ["delivery", "pickup"],
      price: "$$$",
      location: {
        address1: "The Embarcadero",
        address2: "",
        address3: "Pier 5",
        city: "San Francisco",
        zip_code: "94111",
        country: "US",
        state: "CA",
        display_address: [
          "The Embarcadero",
          "Pier 5",
          "San Francisco, CA 94111",
        ],
      },
      phone: "+14157048866",
      display_phone: "(415) 704-8866",
      distance: 5459.162007006186,
    },
    {
      id: "lgD2BDiMtW3UhM6rk3IUNw",
      stage: "lead",
      alias: "chicken-as-cluck-san-francisco",
      name: "Chicken as Cluck",
      image_url:
        "https://s3-media2.fl.yelpcdn.com/bphoto/lzHGEUlhlRCxWJD7LacVEg/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/chicken-as-cluck-san-francisco?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 140,
      categories: [
        {
          alias: "chickenshop",
          title: "Chicken Shop",
        },
        {
          alias: "fooddeliveryservices",
          title: "Food Delivery Services",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7505862896473,
        longitude: -122.395178442908,
      },
      transactions: ["delivery", "pickup"],
      price: "$$",
      location: {
        address1: "1760 Cesar Chavez St",
        address2: null,
        address3: null,
        city: "San Francisco",
        zip_code: "94124",
        country: "US",
        state: "CA",
        display_address: ["1760 Cesar Chavez St", "San Francisco, CA 94124"],
      },
      phone: "+14156700428",
      display_phone: "(415) 670-0428",
      distance: 3805.0064991829518,
    },
    {
      id: "kqk5BoCJU59MC9fH0IB4wQ",
      stage: "lead",
      alias: "kin-khao-san-francisco-2",
      name: "Kin Khao",
      image_url:
        "https://s3-media1.fl.yelpcdn.com/bphoto/zHz6-HG5XuXSZJq2FvNmsQ/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/kin-khao-san-francisco-2?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 2139,
      categories: [
        {
          alias: "thai",
          title: "Thai",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7852278803726,
        longitude: -122.409348137336,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "55 Cyril Magnin St",
        address2: null,
        address3: "",
        city: "San Francisco",
        zip_code: "94102",
        country: "US",
        state: "CA",
        display_address: ["55 Cyril Magnin St", "San Francisco, CA 94102"],
      },
      phone: "+14153627456",
      display_phone: "(415) 362-7456",
      distance: 3604.326557361939,
    },
    {
      id: "wdqRLypbCo7KCyhLNB8mIQ",
      stage: "lead",
      alias: "souvla-san-francisco-3",
      name: "Souvla",
      image_url:
        "https://s3-media3.fl.yelpcdn.com/bphoto/kzOK8tthxodXt9_oSMlSnA/o.jpg",
      is_closed: false,
      url:
        "https://www.yelp.com/biz/souvla-san-francisco-3?adjust_creative=dMmG78pUcjGZXn0N96Wo_w&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=dMmG78pUcjGZXn0N96Wo_w",
      review_count: 457,
      categories: [
        {
          alias: "mediterranean",
          title: "Mediterranean",
        },
        {
          alias: "greek",
          title: "Greek",
        },
      ],
      rating: 4.0,
      coordinates: {
        latitude: 37.7744799,
        longitude: -122.43802,
      },
      transactions: ["delivery"],
      price: "$$",
      location: {
        address1: "531 Divisadero St",
        address2: "",
        address3: null,
        city: "San Francisco",
        zip_code: "94117",
        country: "US",
        state: "CA",
        display_address: ["531 Divisadero St", "San Francisco, CA 94117"],
      },
      phone: "+14154005458",
      display_phone: "(415) 400-5458",
      distance: 1519.7431425358823,
    },
  ],
};
